<?php 
$breadColor = 'orange';
$breadPaths = array('Prestação de contas'=>'prestacao-de-contas2/contas?year=2015');
$lastPath = 'Contas';
include('top.phtml'); 

?>
<?php $meses = array (1 => "Janeiro", 2 => "Fevereiro", 3 => "Março", 4 => "Abril", 5 => "Maio", 6 => "Junho", 7 => "Julho", 8 => "Agosto", 9 => "Setembro", 10 => "Outubro", 11 => "Novembro", 12 => "Dezembro");?>

<div id="dynamic-content">
   <section class="row container-large m-b-0">
    <article class="col s12 m-b-20" id="dynamic-content">
    
    <h1 class="h1 m-b-0 bold upper aug_orange">Prestação de Contas</h1>
        <div>
            <span>Visualize por ano:</span>
            <?php for($i = date('Y'); $i >= 2005; $i--):?>
            <a href="<?php echo HOST;?>prestacao-de-contas2/contas?year=<?php echo $i;?>"  class="bt_mini bt_orange div_left05"><?php echo $i;?></a>
            <?php endfor;?>
            <a href="<?php echo HOST;?>prestacao-de-contas2/doacoes" class="bt_mini bt_blue right">Ir para Doações</a>
            
        </div>
        
        <div>
        <br />
            <?php if(is_array($this->data) and (sizeof($this->data) > 0)):?>
            <?php foreach($this->data as $month => $month_data):?>
            <?php $total = 0;?>
            <table class="datagrid table highlight">
                <thead>
                    <tr>
                        <th colspan="3">
                            <strong class="aug_orange"><?php echo $meses[+$month];?></strong></th>
                    </tr>
                    <tr>
                        <td align="center" width="10%"><strong class="aug_orange">Data</strong></td>
                        <td align="center" width="65%"><strong class="aug_orange">Descrição</strong></td>
                        <td align="center" width="10%"><strong class="aug_orange">Valor</strong></td>
                    </tr>
                </thead>
                
                <tbody>
                <?php foreach($month_data as $row):
                $total += $row->amount;
                ?>
                <tr>
                    <td align="center"><?php echo date('d/m/Y', strtotime($row->date));?></td>
                    <td><?php echo ($row->description);?></td>
                    <td align="right">
                        <span style="float:left">R$</span>
                        <span style="color:#<?php echo ($row->amount >= 0)?'050':'C00';?>"><?php echo number_format($row->amount, 2, ',', '.');?></span>
                    </td>
                </tr>
                <?php endforeach;?>
                </tbody>
                
                <!--
                <tfoot>
                    <tr>
                    <td colspan="2" align="right" style="padding:4px;font-weight:bold;">Subtotal:</td>
                    <td align="right">
                        <span style="float:left">R$</span>
                        <span style="color:#<?php echo ($total >= 0)?'050':'C00';?>"><?php echo number_format($total, 2, ',', '.');?></span>
                    </td>
                    </tr>
                </tfoot>
                -->
            </table>
            <br />
            <?php endforeach;?>
            <?php else:?>
            <p>Não existem dados para o período selecionado</p>
            <?php endif;?>
        </div>

    </article>
</section>