<?php 
$breadColor = 'blue';
$breadPaths = array('Gatinhos para adoção'=>'#', 'Formulário'=>'#');
$lastPath = 'Erro';
include('top.phtml'); 

?>

<section class="row m-b-0">
   <article class="col s10 offset-s1">
       <h2 class="h1 aug_blue">Oooops!</h2>
        <p>Ocorreu um erro ao registrar o seu <b class="aug_blue">pedido de adoção</b>.</p>
        <p>Tente novamente mais tarde. Se o problema persistir, entre em contato conosco.</p>
        <p>Att, <br /> Equipe Adote um Gatinho</p>
        
        <a class="perfil left bt bt_gray m-t-20 aug_blue" href="javascript:history.back()">Voltar</a>
   </article>
</section>
