<?php 
$breadColor = 'purple';
$breadPaths = array();
$lastPath = 'Como adotar um gatinho';
include('top.phtml'); 

?>

<div class="aug_grey_bg">   
		<div class="row container-large m-b-0">
			<h1 class="h1 bold upper aug_purple col s12">COMO FAÇO PARA ADOTAR UM GATINHO?</h1>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info1">&nbsp;</div>
					</div>
					<div class="card-content bottom-align">
						<span class="text_13 bold aug_purple info-title">1. Gatinhos</span>
						<p>Todos os gatinhos do site são vermifugados, vacinados e castrados.</p>
					</div>
				</div>
			</div>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info2">&nbsp;</div>
					</div>
					<div class="card-content bottom-align">
						<span class="text_13 bold aug_purple info-title">2. Escolha do gatinho</span>
						<p>Você entra no site, escolhe um gatinho e clica em "Saiba mais sobre mim". Se esse for o escolhido, você clica em <span class="bold aug_purple"> QUERO ADOTAR</span>.</p>
					</div>
				</div>
			</div>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info3">&nbsp;</div>
					</div>
					<div class="card-content bottom-align">
						<span class="text_13 bold aug_purple info-title">3. Critérios de adoção</span>
						<p>Você lê atentamente os critérios e, caso se encaixe no perfil, clica em <span class="bold aug_purple">EU ME ENCAIXO NO PERFIL</span>.</p>
					</div>
				</div>
			</div>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info4">&nbsp;</div>
					</div>
					<div class="card-content bottom-align">
						<span class="text_13 bold aug_purple info-title">4. Formulário</span>
						<p>Você preenche o formulário e clica em <span class="bold aug_purple">ENVIAR FORMULÁRIO</span>.</p>
						<p>Caso não funcione, envie as respostas para o email indicado no site.</p>
					</div>
				</div>
			</div>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info5">&nbsp;</div>
					</div>
					<div class="card-content bottom-align">
						<span class="text_13 bold aug_purple info-title">5. Resposta</span>
						<p>O voluntário responsável pelo gatinho responde em até 48h.</p>
					</div>
				</div>
			</div>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info6">&nbsp;</div>
					</div>
					<div class="card-content bottom-align">
						<span class="text_13 bold aug_purple info-title">6. Data de Entrega</span>
						<p>A entrega é combinada por email.</p>
						<p>Não cobramos taxa de adoção!</p>
					</div>
				</div>
			</div>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info7">&nbsp;</div>
					</div>
					<div class="card-content bottom-align">
						<span class="text_13 bold aug_purple info-title">7. Entrega</span>
						<p>Um voluntário levará o gato até a sua casa. Antes de soltar o gatinho, ele verificará se a sua casa é segura. Se estiver tudo de acordo, o gatinho é solto!</p>
					</div>
				</div>
			</div>
			<h1 class="h1 bold upper aug_purple col s12">Critérios de adoção do AUG: um resumo</h1>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info8">&nbsp;</div>
					</div>
					<div class="card-content bottom-align"><span class="text_13 bold aug_purple info-title">Segurança</span>
					<p>Só doamos gatinhos para casas e apartamentos seguros, de onde o gatinho não possa sair ou fugir.</p>
					</div>
				</div>
			</div>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info9">&nbsp;</div>
					</div>
					<div class="card-content bottom-align"><span class="text_13 bold aug_purple info-title">Condições financeiras</span>
					<p>O adotante precisa ter condições de alimentar o gatinho, vaciná-lo anualmente e levá-lo ao veterinário sempre que necessário.</p></div>
				</div>
			</div>
			<div class="col s12 m6 l3">
				<div class="card large border_b_purple card-wrapper">
					<div class="card-image p-t-large-card" align="center">
						<div class="info10">&nbsp;</div>
					</div>
					<div class="card-content bottom-align">
						<span class="text_13 bold aug_purple info-title">Posse responsável</span>
						<p>O adotante precisa estar comprometido com o gatinho e disposto a cuidar e se responsabilizar por ele até o final da sua vida.</p>
					</div>
				</div>
			</div>
		</div>
	</div>