<?php 
$breadColor = 'purple';
$breadPaths = array();
$lastPath = 'FeLV: Leucemia Felina';
include('top.phtml'); 

?>

<div class="aug_grey_bg m-b-0">
	    <div class="image-background-text" style="background-image: url('<?php echo HOST;?>img/felv.jpg'); position: relative;">
            <div class="gradiente"></div>
            <article class="col s12 l4 offset-l1 news-title">
                <div class="heading upper aug_purple_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">FeLV</div>
                <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">Leucemia Felina</h2>
                <h3 class="italic white-text text_10 col s12 m6" style="margin-top: -20px;">Temos vários gatinhos positivos para FeLV e, por isso, gostaríamos de contar um pouco do que aprendemos nesses anos de proteção animal sobre a doença.</h3>
            </article>
	    </div>
	    	<article class="row container-large m-b-0">
	    	
	    		<div class="col s12" style="margin-top: 50px; margin-bottom: 50px;">
					<p class="text_10 m-t-10">Temos vários gatinhos positivos para FeLV e, por isso, gostaríamos de contar um pouco do que aprendemos nesses anos de proteção animal sobre a doença.</p>
					<p class="text_10 m-t-10">FeLV é leucemia felina, ou seja, ela é exclusiva de gatos. Ela é causada por um vírus e a contaminação pode acontecer quando gatos se mordem, se lambem ou compartilham caixas de areia, potes de água e comida. As fêmeas grávidas podem passar o vírus para os filhotes via placenta ou amamentação.</p>
					<p class="text_10 m-t-10">Algumas coisas que observamos aqui na ONG:</p>
					<ul class="row text_10 m-t-10 aug_purple offset-s1">
						<li class="col s10 offset-s1 lista-texto">Pode acontecer de metade de uma ninhada ser positiva e metade negativa. É também possível que a mãe seja negativa e os filhotes positivos. A mãe pode ser positiva e os filhos negativos. Não sabemos ainda como isso funciona.</li>
						<li class="col s10 offset-s1 lista-texto">Se o gatinho manifesta a doença (geralmente por anemia, tumores, linfomas, etc.) é preciso um supercontrole para dar sobrevida com qualidade ao animal. </li>
						<li class="col s10 offset-s1 lista-texto">Você pode ter um gato positivo para FeLV convivendo com um negativo desde que o negativo, antes do contato, seja vacinado com a quíntupla felina (2 doses com espera de 15 dias após a segunda dose).</li>
						<li class="col s10 offset-s1 lista-texto">Cada animal reage de uma forma e é difícil prever quais problemas o gatinho pode vir a ter graças à leucemia felina. Por isso, é muito importante que o gatinho seja acompanhado por um veterinário. </li>
						<li class="col s10 offset-s1 lista-texto">Existem gatos que eliminam a FeLV sozinhos ou como costumamos falar, negativam. Já tivemos vários casos assim por aqui.</li>
						<li class="col s10 offset-s1 lista-texto">Os cuidados com um gatinho positivo pra FeLV são iguais aos com qualquer gatinho: a ração deve ser de boa qualidade, as visitas ao veterinário devem ser frequentes e o comportamento dos gatinhos deve ser observado. Qualquer mudança pode ser sinal de problemas e isso vale para todos os gatinhos. </li>
						</ul>
						<p class="text_10 m-t-10">Deixe o preconceito de lado e dê um final feliz a um gatinho positivo para FeLV! </p>
						<p class="text_10 m-t-10">Importante: O texto que escrevemos é feito com base na nossa experiência com nossos gatinhos. Consulte um veterinário para mais informações. </p>
					
				</div>
			</article>
		</div>