<?php 
$breadColor = 'purple';
$breadPaths = array();
$lastPath = 'FIV: A Aids Felina';
include('top.phtml'); 

?>
  

<div class="aug_grey_bg m-b-0">
	    <div class="image-background-text" style="background-image: url('<?php echo HOST;?>img/FIV.jpg'); position: relative;">
            <div class="gradiente"></div>
            <article class="col s12 l4 offset-l1 news-title">
                    <div class="heading upper aug_purple_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">FIV</div>
                    <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">A Aids felina</h2>
                    <h3 class="italic white-text text_10 col s12" style="margin-top: -20px;">Ter um gatinho com FIV (aids felina) em casa é mais tranquilo do que se pensa. Com alguns cuidados, ele poderá ter uma vida longa e feliz.</h3>
            </article>
       </div>
	    	<article class="row container m-b-0">
	    	
	    		<div class="col s12" style="margin-top: 50px; margin-bottom: 50px;">
					<p class="text_10 m-t-0">Basicamente, o vírus da FIV faz com que o animal tenha uma imunidade baixa, ou seja, ele poderá não ser capaz de combater doenças graves ou até mesmo simples como uma gripe. Então, se você descobrir que o seu gato é portador ou se você decidir adotar um gatinho com aids felina, saiba que será preciso cuidar da sua saúde preventivamente e estressá-lo o menos possível (evitar banhos, visitas que o assustem, etc.) para que ele fique sempre bem. O veterinário poderá indicar também suplementos para fortalecer o sistema imunológico.</p>
					<p class="text_10 m-t-10">A transmissão da FIV é feita exclusivamente de gato para gato (isso mesmo: a FIV não passa para cachorros e nem para pessoas).  Ela pode acontecer de mãe para filho, via placenta ou amamentação, por mordidas profundas durante brigas ou no ato sexual. Não deixar o seu gato ter acesso à rua é superimportante, pois você não tem como controlar se ele irá brigar com um gatinho portador.</p>
					<p class="text_10 m-t-10">Com as devidas precauções, um gatinho FIV pode viver 10 anos ou mais. A maneira como o gato infectado irá apresentar a doença dependerá da fase da vida em que ele foi contaminado. Filhotes e adolescentes tentem a desenvolver a doença de uma forma mais agressiva.</p>
					<p class="text_10 m-t-10">Com a nossa experiência no Adote um Gatinho, notamos que quase todos os positivos que chegam são machos maduros não castrados. São gatos que passaram a vida toda atrás de fêmeas, cruzando com todas as gatas no cio que encontraram pelo caminho e, em algum momento, se contaminaram. Esses gatos quase nunca apresentam problemas secundários de saúde pois a FIV foi adquirida tardiamente. São raros os filhotes que chegam ao AUG com FIV, mas acontece.</p>
					<p class="text_10 m-t-10">Conhecemos algumas pessoas que tem gatos portadores e não portadores convivendo em casa. Não ocorreu contágio porque os animais em questão são muito pacatos, não brigam e, castrados, não vão cruzar. Não existe garantia de que a transmissão nunca acontecerá. Por isso, recomendamos que gatinhos FIV sejam adotados para serem filhos únicos ou por pessoas que já possuam gatos portadores. </p>

				<div class="col s12 m5 text_15 pull-m1 m-t-20 m-b-20 text-right aug_purple" style="font-weight: lighter;"><em>"Com as devidas precauções, um gatinho FIV pode viver 10 anos ou mais. A maneira como o gato infectado irá apresentar a doença dependerá da fase da vida em que ele foi contaminado. Filhotes e adolescentes tentem a desenvolver a doença de uma forma mais agressiva."</em></div>


					<p class="text_10 m-t-10">Se você não sabe se o seu gato é FIV, vale a pena tirar a dúvida. O teste (que também analisa se o gato é portador de FeLV - leucemia felina) é realizado em clínicas e laboratórios veterinários por meio de uma coleta de sangue. Se o seu gato tem acesso à rua, vale a pena refazer o teste depois de 30 dias pois pode dar falso positivo.</p>
					<p class="text_10 m-t-10">Se o seu gatinho for portador, aumente a frequência das consultas de check-up e peça exames de sangue para acompanhar a saúde. Fique de olho no peso, na pelagem, nas gengivas e nos dentes, nas orelhas e no apetite do gatinho. Gatos FIV estão sujeitos a doenças oportunistas como dermatites, estomatites, periodontites, entre outras. Geralmente, os portadores acabam morrendo dessas doenças secundárias e não da aids em si. Preste atenção no comportamento do seu gatinho: se ele passar a comer e beber mais ou menos água, ficar mais quieto ou mais agitado, se ele emagrecer de repente ou tiver febre, é hora de consultar o veterinário. Isso vale para todos os gatos, não só os positivos para FIV: gatinhos são discretos e geralmente descobrimos que estão com algum problema quando notamos mudanças no comportamento.</p>
					<p class="text_10 m-t-10">Aqui na ONG a gente já notou uma certa relação dos FIV com gengivites e periodontites, os demais problemas que citamos acima ainda não foram notados nesses nossos 13 anos de existência. Ou seja, é o que falamos no início: gatinhos FIV podem viver por bastante tempo e bem, não necessariamente serão gatos que darão trabalho.</p>
					<p class="text_10 m-t-10">Se você ainda não tem um bichano, considere adotar um gatinho portador de FIV. Devido ao preconceito eles têm poucas chances de adoção e são tão encantadores, brincalhões, carinhosos e felizes quanto os demais gatinhos. Considere uma adoção especial. Eles também merecem um lar. </p>
					<p class="text_10 m-t-10">Importante: O texto que escrevemos é feito com base na nossa experiência com nossos gatinhos. Consulte um veterinário para mais informações. </p>
				</div>
			</article>
		</div>