<!-- VIEW NOVA  -->
<?php 
$breadColor = 'purple'; // aqui ele escolhe a cor de fundo da busca (orange, purple, blue)
$breadPaths = array();  // Pra definir os caminhos intermediários do breadcrumb, é só colocar nesse formato 'chave'=> 'valor' separado por vírgulas
$lastPath = 'Quero adotar'; // a página atual, último nível do breadcrumb
include('top.phtml'); // view em si

?> 

<div class="aug_grey_bg">
  <div class="row container-large m-b-0">

    <div class="col s12">
     <h1 class="col s12 aug_purple bold upper h1">Quero Adotar</h1>
       
       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>gatinhos-para-adocao">
                   <div align="center">
                     <div class="activator icon-purple ic-cat-tooth info-quero-adotar"></div>
                   </div>
<!--                     <img class="activator" src="<?php echo HOST;?>__novo/img/gatinhos-para-adocao.jpg" /> -->
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Gatinhos para adoção</span>
                <p class="m-t-10">Veja os gatinhos que estão a espera de um lar e de muito carinho</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>gatinhos-para-adocao" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>adocoes-especiais2">
                   <div align="center">
                     <div class="activator icon-purple ic-looking-cat info-quero-adotar"></div>
                   </div>
<!--                     <img class="activator" src="<?php echo HOST;?>__novo/img/gatinhos-para-adocao.jpg" /> -->
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Adoções Especiais</span>
                <p class="m-t-10">Eles também merecem um lar. Conheça os nossos gatinhos especiais e se apaixone.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>gatinhos-para-adocao" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>como-adotar-um-gatinho">
                    <div align="center">
                     <div class="activator icone-adocao info-quero-adotar"></div>
                    </div>
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Como faço para adotar um gatinho?</span>
                <p class="m-t-10">Veja aqui o fluxograma com o passo a passo.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>como-adotar-um-gatinho" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>  

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>
__novo/politica-de-adocao.html">
                    <div align="center">
                     <div class="activator icon-purple ic-ok-doc info-quero-adotar"></div>
                    </div>
                    <!-- <img class="activator" src="<?php echo HOST;?>__novo/img/politica-de-adocao.jpg" alt="" /> -->
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Política de adoção</span>
                <p class="m-t-10">Conheça os critérios de adoção do Adote um Gatinho.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>
__novo/politica-de-adocao.html" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

      <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>cartinhas2">
                    <div align="center">
                     <div class="activator icon-purple ic-letter info-quero-adotar"></div>
                    </div>
                    <!-- <img class="activator" src="<?php echo HOST;?>__novo/img/depoimentos.jpg" alt="" /> -->
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Cartinhas</span>
                <p class="m-t-10">Finais felizes! Nossos gatinhos mandam notícias dos seus novos lares!</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>cartinhas2" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>      
    
      <h1 class="col s12 aug_purple bold upper h1" id="Informacoes-importantes">Informações Importantes</h1>
      <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>
__novo/preparado-para-adotar.html">
                    <img class="activator" src="<?php echo HOST;?>__novo/img/preparado-para-adotar.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Preparado para adotar?</span>
                <p class="m-t-10">Pegar um gatinho pra criar é muito mais do que dar ração e água. Veja se você realmente está preparado e tem condições de adotar um!</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>
__novo/preparado-para-adotar.html" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>
       
       
       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                <a href="<?php echo HOST;?>um-ou-dois-gatinhos">
                    <img class="activator" src="<?php echo HOST;?>__novo/img/um-ou-dois-gatinhos.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Um ou dois gatinhos?</span>
                <p class="m-t-10">O que é melhor? Adotar de cara um ou dois gatinhos? A maioria das pessoas tem medo de adotar dois gatinhos de uma vez. Bobagem!</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>um-ou-dois-gatinhos" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>
       
       
       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
               <a href="<?php echo HOST;?>a-importancia-da-castracao2">
                    <img class="activator" src="<?php echo HOST;?>__novo/img/importancia-castracao.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">A importância da castração</span>
                <p class="m-t-10">Castrar seu gatinho é importante! Confira os motivos e também locais onde levar seu bichinho para ser operado a um custo mais acessível.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>a-importancia-da-castracao2" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>
       

      <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
               <a href="<?php echo HOST;?>telas-nas-janelas2">
                    <img class="activator" src="<?php echo HOST;?>__novo/img/telas-nas-janelas.jpg" alt="" />
                    
              </a>
              
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Telas nas janelas</span>
                <p class="m-t-10">Telas são item obrigatório para quem mora em apartamento e quer adotar um gatinho. Não é frescura, não! Veja o porquê.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>telas-nas-janelas2" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

      <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>toxoplasmose2">
                    <img class="activator" src="<?php echo HOST;?>__novo/img/toxoplasmose.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Toxoplasmose</span>
                <p class="m-t-10">Sim, a toxoplasmose pode ser transmitida pelos gatos. Mas é muito raro pegar a doença de um bichano. Saiba o que é mito e o que é verdade em relação ao assunto.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>toxoplasmose2" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>fiv">
                    <img class="activator" src="<?php echo HOST;?>__novo/img/FIV.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">FIV: a Aids Felina</span>
                <p class="m-t-10">Ter um gatinho com FIV (aids felina) em casa é mais tranquilo do que se pensa. Com alguns cuidados, ele poderá ter uma vida longa e feliz.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>fiv" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>felv">
                    <img class="activator" src="<?php echo HOST;?>__novo/img/felv.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">FeLV: Leucemia Felina</span>
                <p class="m-t-10">FeLV é leucemia felina, ou seja, ela é exclusiva de gatos. Ela é causada por um vírus e a contaminação pode acontecer quando gatos se mordem, se lambem ou compartilham caixas de areia, potes de água e comida.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>felv" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>__novo/pif.html">
                    <img class="activator" src="<?php echo HOST;?>__novo/img/pif.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">PIF: Peritonite Infecciosa Felina</span>
                <p class="m-t-10">A PIF é uma das doenças que mais assustam os donos de gatos, mas não é preciso entrar em pânico. Uma porcentagem muito pequena de gatos adquire a doença.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>__novo/pif.html" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>
    </div>      
  </div> 
</div>   
