<?php 
$breadColor = 'orange';
$breadPaths = array();
$lastPath =  'Socorro! Encontrei um gatinho!';
include('top.phtml'); 

?>


<div class="aug_grey_bg m-b-0">
	<div class="image-background-text" style="background-image: url('<?php echo HOST;?>__novo/img/resgate.jpg'); position: relative;">
		<div class="gradiente"></div>

		<article class="col s12 l4 offset-l1 news-title">
			<div class="heading upper aug_orange_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">Resgate</div>
			<h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">Socorro! Encontrei um gatinho!</h2>
			<h3 class="italic white-text text_10 col s12 m6" style="margin-top: -20px;">Todo dia milhares de gatinhos nascem ou são abandonados nas ruas. É impossível para os protetores e ONGs resgatar todos – não há espaço nem dinheiro.</h3>
		</article>

	    	<!-- <div class="row">
				<div class="col s12 offset-s1 text_10 aug_orange_bg white-text" style="padding: 10px 15px; display: inline-block;">Resgate</div>
	    		<h1 class="col l12 offset-l1 m6 offset-m1 s10 h1 responsive white-text bold upper bottom-align bold p-10 aug_orange_bg" style="bottom: 0px; display: inline-block;">&nbsp;Socorro! Encontrei um gatinho!</h1>
	    	</div> -->
	    </div>
	    <article class="row col s12 container m-b-20" style="height: inherit; margin-bottom: 5rem;">
	    	
	    	<div class="col s12">
	    		
	    		<h1 class="italic aug_orange text-center bold text_15">Os animais, uma vez domesticados, passaram a depender de nós. Não espere que outra pessoa vá ajudar um animal doente, faminto, ferido, com frio ou medo. Faça a sua parte! Como? A gente te orienta!</h1>
	    	</div>

	    	<div class="col s12 m4 m-t-0">
	    		<div class="text_15 bold upper aug_orange m-t-10 m-b-10">Resgate</div>
	    		<p class="text_10">Você vai precisar de uma caixa de transporte para capturar o gatinho. Em caso de gatos muito assustados, medrosos ou ariscos, você pode chamar um capturador profissional. O serviço é cobrado e muito bem feito.</p>
	    		<ul class="m-t-10">
	    			<li class="text_10 m-t-10" style="margin-top: 5px;"><span class="bold">Rogério</span> - (11) 99503-4258</li>
	    			<li class="text_10" style="margin-top: 5px;"><span class="bold">Raquel</span> - (11) 99880-0754</li>
	    			<li class="text_10" style="margin-top: 5px;"><span class="bold">Nico</span> - (11) 98385-9244</li>
	    			<li class="text_10" style="margin-top: 5px;"><span class="bold">Fabio</span> – (11) 2825-0552 / 98849-4301 (claro) / 94967-5587 (tim) / 97455-2416 (vivo)</li>
	    			<li class="text_10" style="margin-top: 5px;"><span class="bold">Eduardo (Bicho Brother)</span> - (11) 94701- 1776</li>
	    		</ul>
	    	</div>
	    	<div class="col s12 m8 m-t-0">
	    		<div class="text_15 bold upper aug_orange m-t-10">Acomodando o gatinho resgatado</div>
	    		<p class="text_10 m-t-10">Depois do resgate, você precisa de um local na sua casa para abrigá-lo. Pode ser na área de serviço, no lavabo, num banheirinho, até mesmo dentro do box.</p>
	    		<p class="text_10 m-t-10">Se você já tem animais em casa, nunca coloque o gato resgatado em contato com eles. Mesmo sem aparentar, o resgatado pode ter alguma doença contagiosa que irá colocar em risco os gatos residentes. Mesmo que você já o tenha levado ao veterinário, algumas doenças ficam incubadas e só vão se manifestar tempos depois.</p>
	    		<p class="text_10 m-t-10">Leve o gatinho ao veterinário para passar por um check-up e, dependendo do caso, até tomar um bom banho.</p>
	    		<p class="text_10 m-t-10"><a href="http://arcabrasil.org.br/index.php/lista-vets-sp/" target="_blank">AQUI</a> você encontra uma série de veterinários que atendem com preços mais acessíveis ou você pode procurar o <a href="http://www.prefeitura.sp.gov.br/cidade/secretarias/saude/vigilancia_em_saude/controle_de_zoonoses/" target="_blank">CCZ</a> (Centro de Controle de Zoonoses) para realizar a castração gratuitamente.</p>
	    	</div>
	    </article>
	    <article class="row container col s12 m-b-0 m-t-20">
	    	
	    	<div class="col s12 m6 l4">
	    		<div class="text_15 bold upper aug_orange">DIVULGAÇÃO</div>
	    		<p class="text_10 m-t-10 m-b-10">Depois de castrado nós ajudamos você a divulgá-lo! Basta publicar uma foto, a cidade e região onde está o gatinho e seus contatos na página <a href="http://www.facebook.com/augrepassa" target="_blank" class="aug_orange bold truncate">facebook.com/augrepassa.</a></p>
	    		<p class="text_10 m-t-10 m-b-10">Divulgue também pelo seu bairro, distribuindo pequenos cartazes em petshops, clínicas veterinárias e comércios em geral.</p>
	    		<p class="text_10 m-t-10 m-b-10">Se cada um ajudar um gatinho que cruzar o seu caminho, aos poucos o mundo será um lugar melhor. Contamos com vocês!</p>
	    	</div>
	    	<div class="col s12 m6 l5">
	    		<div class="text_15 bold upper aug_orange">ME AJUDA, AUG!</div>
	    		<p class="text_10 m-t-10">Se você é de São Paulo e quer pedir nossa ajuda para um gatinho que você resgatou, envie um e-mail para <a href="mailto:resgates@adoteumgatinho.org.br" class="aug_orange bold truncate">resgates@adoteumgatinho.org.br.</a></p>
	    		<p class="text_10 m-t-10 m-b-20"> Se tivermos vaga, ele virá para a ONG e será doado conforme os nossos critérios de adoção. Demoramos até 48h para responder os e-mails. Por isso, é importante que, em caso de emergência, você não espere a nossa resposta e leve o gato ao veterinário imediatamente para uma avaliação do estado de saúde dele. Quanto mais rápido o gatinho for atendido, maior a chance de você conseguir salvar a vida dele. Em alguns casos, minutos podem fazer a diferença!</p>
	    	</div>
	    	<div class="col s12 l3">
	    		<div class="text_15 bold upper aug_orange">Preparando o gatinho para a adoção</div>
	    		<p class="text_10 m-t-10">Comece com os vermífugos e as vacinas, e não se esqueça de doar o gatinho castrado!</p>
	    		<p class="m-t-10  m-b-20">Respeite o estado de saúde do animal e siga sempre as orientações de um veterinário antes de realizar qualquer procedimento.</p>
	    	</div>
	    	<div class="card white card-wrapper m-b-20 col s12" align="center" style="padding: 3rem;">
	    		<span class="card-title aug_orange bold text_15 m-b-10 upper" style="background-color: transparent; text-shadow: none;">Importante</span>
	    		<p class="m-t-10">Todo e qualquer animal resgatado <span class="aug_orange bold">DEVE SER CASTRADO ANTES DE SER DOADO</span>, assim você terá a certeza de que ele não vai continuar se reproduzindo e aumentando a população de animais de rua.</p>
	    	</div>
	    </article>
	</div>