<?php 
$breadColor = 'blue';
$breadPaths = array();
$lastPath = 'Como posso ajudar?';
include('top.phtml'); 
?>

        <div class="aug_grey_bg m-b-0">
            <div class="image-background-text" style="background-image: url('<?php echo HOST; ?>__novo/img/ajudar.jpg'); position: relative; background-position: right;">
            <div class="gradiente"></div>
                <main class="col s12 l4 offset-l1 news-title">
                        <div class="heading upper aug_blue_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">Quero Ajudar</div>
                        <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">COMO POSSO AJUDAR?</h2>
                        <h3 class="italic white-text text_10 col s12" style="margin-top: -20px;">Quando cuidávamos de um punhadinho de gatos, nós nos apertávamos mas dávamos conta de bancar com dinheiro do próprio bolso as vacinas, castrações, tratamentos e alimentação dos gatinhos do site. </h3>
                </main>
            </div>
            <article class="row container m-b-0">
            
                <div class="col s12 m-b-0" style="margin-top: 50px; margin-bottom: 50px;">
                    <p class="text_10 m-t-0">Aos poucos, as pessoas foram se interessando pelo nosso trabalho e começaram a nos ajudar. 
                    Fomos tirando mais e mais gatinhos das ruas. 
                    Hoje, todo o trabalho do Adote um Gatinho não seria possível sem as doações, sem a ajuda dessas pessoas maravilhosas que contribuem regular ou esporadicamente com o nosso trabalho. Afinal, ainda não conseguimos nosso sonhado patrocínio...
                    </p>
                    <p class="text_10 m-t-10">Temos medo que o dinheiro falte, que nossos gatinhos passem por dificuldades, jamais daríamos conta dessa turma toda sozinhas. E é por isso que as doações, em rações, dinheiros, produtos, são essenciais a manutenção e continuidade do nosso trabalho... não contamos com patrocínio, não tem ninguém por trás da gente. 
                    </p>
                    <p class="text_10 m-t-10">Ajude os gatinhos do Adote um Gatinho! 
                    Dê uma olhada na lista abaixo e nos ajude com o que estiver ao seu alcance. Toda ajuda é bem-vinda! </p>
                </div>

                <div class="col s12 m-t-0">
                    <h4 class="text_15 bold upper aug_blue m-t-0 m-b-10 text-center">Doações em dinheiro</h4>
                    <p>O dinheiro que recebemos de doação é usado para pagarmos cirurgias (inclusive as de castração), tratamentos, internações, compra de vacinas e de tudo o que estiver faltando para os gatinhos. 
                    Consideramos o tipo de doação "mais útil", pois acabará atendendo às nossas prioridades do momento.</p>
                    <div class="row">
                        <div class="container">
                            <div class="col s12 card white card-wrapper m-b-20 m-t-20" style="padding: 3rem; display: inline-block;">
                                <h4 class="aug_blue bold text_10 m-b-10 m-t-0 upper text-center" style="background-color: transparent; text-shadow: none;">Doações em dinheiro podem ser feitas diretamente na conta da ONG
                                </h4>

                                <p class="bold aug_blue m-t-10 text-center">Razão Social: Adote um Gatinho</p>
                                <p class="m-b-10 text-center"><strong>CNPJ:</strong> 08.858.329/0001-08</p>

                                <div class="m-t-10" style="display: inline-block;">
                                    <p><strong>Itaú:</strong> 0341</p>
                                    <p><strong>Agência:</strong> 2970</p>
                                    <p><strong>C/C:</strong> 12869-6</p>
                                </div>
                                <div class="m-t-10 text-right hide-on-small-only" style="display: inline-block; float: right;">
                                    <p><strong>Bradesco:</strong> 0237</p>
                                    <p><strong>Agência:</strong> 3334</p>
                                    <p><strong>C/C:</strong> 6253-7</p>
                                </div>
                                <div class="m-t-10 hide-on-med-and-up">
                                    <p><strong>Bradesco:</strong> 0237</p>
                                    <p><strong>Agência:</strong> 3334</p>
                                    <p><strong>C/C:</strong> 6253-7</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="m-b-10">Se você tiver como ajudar depositando direto na nossa conta, preferimos. 
                    Esse dinheiro será 100% aproveitado pelos gatinhos.</p>

                    <p class="m-b-10">Se você preferir emitir um boleto, fazer transferência para contas de outros bancos ou pagar com cartão de crédito, estamos cadastrados no sistema PAGSEGURO, do UOL, que permite que você faça sua doação com segurança. </p>

                    <div class="video-container m-b-10">
                        <object id="player_12866592" width="457" height="368" data="http://player.mais.uol.com.br/embed_v2.swf?mediaId=12866592&amp;ver=1" type="application/x-shockwave-flash"><param name="allowfullscreen" value="true"><param name="allowscriptaccess" value="always"><param name="wmode" value="window"><param name="src" value="http://player.mais.uol.com.br/embed_v2.swf?mediaId=12866592&amp;ver=1"><noscript>&lt;a href="http://tvuol.uol.com.br/assistir.htm?video=12866592"&gt;Adote um Gatinho usa o PagSeguro para receber doações&lt;/a&gt;</noscript></object>
                    </div>

                    <p class="m-b-10">Esse sistema nos cobra uma pequena porcentagem, por isso não é 100% aproveitado pelos gatinhos, mas é uma maneira muito fácil e prática de ajudar sem sair de casa.</p>
                    <p class="m-b-10">As taxas cobradas da gente são:</p>
                    <p class="m-b-10">Taxas PagSeguro para as contas Vendedor e Empresarial</p>

                    <div class="col s12">
                    <ul class="m-b-10 collection">
                            <li class="collection-item"><span class="bold aug_blue">Recebimentos à vista</span> <br>
                            (TEFs e Boletos)    <strong style="float: right; margin-top: -11px;">0,9%</strong></li>
                            <li class="collection-item"><span class="bold aug_blue"> Recebimentos a prazo</span> <br>
                            (cartão de crédito) <strong style="float: right; margin-top: -11px;">4,59%</strong></li>
                        </ul>
                    </div>

                    <p class="m-b-10">Clique no botão abaixo e faça sua doação:</p>
                    <form action="https://pagseguro.uol.com.br/checkout/v2/donation.html" method="post" target="pagseguro" class="m-b-10"><input type="image" name="submit" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/doacoes/94x52-doar-assina.gif" alt="Pague com PagSeguro é rápido, grátis e seguro!"></form>

                    <p class="m-b-10">Por favor, não deixe de nos avisar o dia e o valor da sua doação. Fazemos questão de colocar seu nome lá! ;) .
                    <span class="truncate" style="display: inline;">Escreva para <a href="mailto:informacoes@adoteumgatinho.org.br" class="aug_blue bold truncate">informacoes@adoteumgatinho.org.br</a></span></p>

                </div>

                


                <div class="m-t-0 col s12">
                    <h4 class="text_15 bold upper aug_blue m-t-0 m-b-10 text-center">Doando sua NF Paulista</h4>
                    <p>Existem duas maneiras de você doar suas notas fiscais SEM CPF para ajudar nosso gatinhos.</p>

                        <h5 class="heading upper aug_blue_bg white-text bold m-t-20 text_10" style="padding: 2px 15px; display: inline-block;">Enviando por email</h5>
                        <p class="m-t-10 m-b-10">Ao fazer suas compras peça sempre a nota fiscal sem CPF. 
                        <p class="m-b-10">Junte quantas notas você quiser. </p>
                        <p class="m-b-10">Em seguida fotografe com o celular ou escaneie.</p> 
                       <p class="m-b-10 truncate"> Aí é só enviar para: <a href="mailto:notafiscal@adoteumgatinho.org.br" class="bold aug_blue">notafiscal@adoteumgatinho.org.br</a> </p>

                    <h5 class="heading upper aug_blue_bg white-text bold m-t-20 text_10" style="padding: 2px 15px; display: inline-block;">ENTREGANDO PESSOALMENTE OU POR CORREIO</h5>
                        <p class="m-t-10 m-b-10">Caso você prefira entregar suas notas pessoalmente ou via correio, envie um e-mail para <a href="mailto:informacoes@adoteumgatinho.org.br" class="bold aug_blue truncate" style="display: inline;">informacoes@adoteumgatinho.org.br</a> e nós diremos como. </p>
                   
                        <p class="m-b-10">Atenção. O prazo para doação das notas é sempre dia 10 do mês seguinte. Por exemplo, uma nota emitida em fevereiro deve ser enviada até dia 10 de março. E assim por diante. </p>

                        <p class="m-b-10"><span class="bold aug_blue">IMPORTANTE!</span> Nunca forneça o nosso CNPJ no ato da compra, pois assim você inviabiliza o uso desta nota fiscal.</p>

                        <p class="m-b-10">Precisando de mais alguma informação, é só falar com a gente.</p>

                       <p class="m-b-10"> Aguardamos a sua nota fiscal.</p>
                   
                </div>
                 <div class="col s12 m-t-0">
                    <h4 class="text_15 bold upper aug_blue m-t-0 m-b-10 text-center">Doações em produtos</h4>
                    <p class="m-b-10">Aceitamos doações de ração, areia, remédios, caminhas, caixas de transporte, cobertores e tudo o que servir para gatinhos. </p>
                    
                    <p class="m-b-10">Para saber como entregar sua doação pessoalmente, escreva para <a href="mailto:informacoes@adoteumgatinho.org.br" class="aug_blue bold truncate" style="display: inline;">informacoes@adoteumgatinho.org.br</a></p>

                    <p class="m-b-10">Após, a compra, envie um email para <a href="mailto:informacoes@adoteumgatinho.org.br" class="bold aug_blue truncate" style="display: inline;">informacoes@adoteumgatinho.org.br</a>. Assim podemos conferir a entrega e colocar o seu nome na prestação de contas do site.</p>
                </div>
                 <div class="col s12 m-t-0">
                    <h5 class="heading upper aug_blue_bg white-text bold m-t-20 text_10 m-b-20" style="padding: 2px 15px; display: inline-block;">Produtos que sempre precisamos</h5>

                    <ul class="collection">
                        <li class="collection-item"><span class="text_15 bold aug_blue">Ração</span><br>qualquer marca (damos preferência para rações super premium).</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Patês</span><br>qualquer marca. Se você deseja doar especificamente para gatinhos doentes, que precisam ser alimentados na boca com ajuda de uma seringa ou bebês em fase de desmame, aceitamos A/D (Hills) ou Recovery (Royal Canin). </li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Areia</span><br>qualquer marca</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Vermífugos</span><br>qualquer marca (sugestões: Drontal, Endal, Helfine e Profender)</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Remédios veterinários</span><br>
                        <strong>1. Comprimidos/cápsulas:</strong> Flotril, Enropet, Baytril ou Zelotril 50 mg, Baytri 15 mg, Zitrex 100, Doxy 100, Dozy Suspensão, Sinulox 50 mg, Stomorgil 2 mg, Stomorgil 10 mg, Tramadol 12 mg, Ketofen 5 mg, Meticorten 5mg, ITL 25 mg, ITL 50 mg, Giardicid 50mg, Maxicam 0,5mg, Petprazol.<br>
                        <strong>2. Colírios:</strong> Ciprovet<br>
                        <strong>3.Solução/Suspensão/Gotas:</strong> Mucomucil, Pulmonil, Acepran, Natalene<br>
                        <strong>4. Ampolas:</strong> Ranitidina, Complexo B, Gentamicina, Metoclopramida, Ornitagin<br>
                        <strong>5. Pomadas:</strong> Cicatrilex, Vulketan</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Remédios humanos</span><br>
                        <strong>1. Comprimidos/Cápsulas:</strong> Cobavital, Metronidazol, Legalon 70, Secnidazol, Floratil 100<br>
                        <strong>2. Colírios: </strong>Tobramicina colírio, Still colírio, Maxitrol colírio, Vigamox colírio<br>
                        <strong>3. Pomadas: </strong>Terramicina pomada oftálmica, Epitezan pomada oftálmica<br>
                        <strong>4. Solucão/Suspensão:</strong> Leucogen, Amoxicilina, Azitromicina, Fluimucil, Rinofluimucil, Rinosoro, Gardenal, Dipirona Sódica, Predsim<br>
                        <strong>5. Ampolas: </strong>Fluimucil, Ranitidina, Complexo B, Metoclopramida, Ampicilina, Ondasentrona, Tramadol</li>
                        <li class="collection-item"><span class="aug_blue text_15 bold">Soro fisiológico e ringer lactato</span> <br>(aplicação subcutânea e endovenosa).<br></li>
                        <li class="collection-item"><span class="aug_blue text_15 bold">Luvas, algodão, gaze, seringas de 1ml, 3ml, 5 ml e 10 ml, agulhas, equipo, scalp 21 e 23.</span></li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Fraldas</span><br>os gatos que necessitam de fraldas usam 2 Pampers por dia, tamanhos G e XG. Infelizmente não aceitamos outras marcas porque são mais "duras" e acabam criando feridas na dobra das pernas deles.</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Vacinas</span><br>quádrupla felina e anti-rábica</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Anti-pulgas</span> <br>qualquer um</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Caixas de transporte</span><br>qualquer tamanho, de preferência de plástico, para que possa ser esterelizada</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Camas e cobertores</span><br> de qualquer tamanho e material</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Almofada térmica</span><br> à venda em casas cirurgicas (importante para recém-nascidos órfãos em pós-operatório ou recém chegados, que não conseguem manter a temperatura corporal)</li>
                        <li class="collection-item"><span class="text_15 bold aug_blue">Tapetes higiênicos </span><br>de qualquer tamanho</li>
                    </ul>
                </div>
                <div class="col s12">
                    <h4 class="text_15 bold upper aug_blue">Outras formas de ajudar</h4>
                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Apadrinhando um gatinho</span>
                        <p class="m-b-10 m-t-10">Seja madrinha ou padrinho de um gato sem ou com poucas chances de adoção. </p>
                        <p class="m-b-10">Você faz uma contribuição fixa mensal e ajuda a sustentar o gatinho escolhido.</p>
                         <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.adoteumgatinho.com.br/apadrinhamento" target="_blank">Clique Aqui</a>
                         </div>

                    </div>
                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue_btn aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Comprando na nossa lojinha</span>
                        <p class="m-b-10">Na lojinha temos produtos da marca Adote um Gatinho e produtos de parceiros, que revertem uma porcentagem das vendas para o nosso projeto. </p>
                        <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.auglojinha.com.br/" target="_blank">Clique Aqui</a>
                        </div>
                    </div>
                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Participando de nossas rifas</span>
                        <p class="m-b-10">Sempre temos uma rifa de algum produto "de gatos" ou "para gatos" no ar. </p>
                        <p class="m-b-10">Você concorre ao prêmio e ajuda os nossos peludinhos.</p>
                       <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.adoteumgatinho.com.br/rifas" target="_blank">Clique Aqui</a>
                        </div>
                    </div>
                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Divulgando o nosso trabalho</span>
                        <p class="m-b-10">Indique nosso trabalho para seus amigos, professores, etc</p>
                        <p class="m-b-10">Imprima um folheto do AUG e o coloque em murais de pet shops e clínicas veterinárias</p>
                        </div>
                    </div>
                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Comprando no site da Pet Love</span>
                        <p class="m-b-10">- Faça as suas compras através do link a seguir e parte da sua compra e revertida em doações para o AUG </p>
                        <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.petlove.com.br/?utm_source=adote-um-gatinho&utm_medium=afiliados" target="_blank">Clique Aqui</a>
                        </div>
                    </div>
                    <div class="col s12 m6 l4 hide-on-small-only">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Utilizando os serviços do Pet Memorial</span>
                        <div style="height: 50%; overflow-y: auto;">
                            <p>A gente sempre espera que você não precise, mas caso seu bichinho (gato, cachorro, coelho, passarinho, cavalo, etc) partir para o céu e você optar pela cremação, ao ligar para a vendedora Marcia do Pet Memorial você pode ajudar o AUG. Basta  dizer que foi indicado pelo Adote um Gatinho você estará contribuindo com R$50 ou R$100 (dependendo do plano escolhido). A promoção vale para os planos preventivos também. </p>
                            <p class="m-b-10 bold aug_blue">Telefone: 0800 772 8885 </p>
                        </div>
                        <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.petmemorial.com.br/" target="_blank">Clique Aqui</a>
                        </div>
                    </div>
                    <div class="col s12 m6 l4 hide-on-med-and-up">
                        <div class="large card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Utilizando os serviços do Pet Memorial</span>
                        <div>
                            <p>A gente sempre espera que você não precise, mas caso seu bichinho (gato, cachorro, coelho, passarinho, cavalo, etc) partir para o céu e você optar pela cremação, ao ligar para a vendedora Marcia do Pet Memorial você pode ajudar o AUG. Basta  dizer que foi indicado pelo Adote um Gatinho você estará contribuindo com R$50 ou R$100 (dependendo do plano escolhido). A promoção vale para os planos preventivos também. </p>
                            <p class="m-b-10 bold aug_blue">Telefone: 0800 772 8885 </p>
                        </div>
                        <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.petmemorial.com.br/" target="_blank">Clique Aqui</a>
                        </div>
                    </div>
                </div>
            </article>
        </div>