<h2>Padrinhos cadastrados</h2>

<p><a href="<?php echo HOST;?>adm/padrinhos/adicionar/">Adicionar padrinho</a></p>

<form name="godfather" id="godfather" action="<?php echo HOST;?>adm/padrinhos/" method="post">
    <p>
    Buscar Padrinho: <input type="text" id="search" name="search" value="<?php echo $this->search; ?>" />
    Ordenar: 
    <select type="select" id="order" name="order"> 
        <option value="nome ASC" <?php if ($this->order=="nome ASC") echo "selected=\"selected\""; ?>>Alfabética A-Z</option>
        <option value="nome DESC" <?php if ($this->order=="nome DESC") echo "selected=\"selected\""; ?>>Alfabética Z-A</option>
        <option value="data_inicio DESC" <?php if ($this->order=="data_inicio DESC") echo "selected=\"selected\""; ?>>Data do Cadastro</option>
    </select>
    
    <input type="submit" value="OK" />
    
    <span class="pagination">
            <?php if ($this->total_pages > 0) { ?>Página <?php if(($this->total_pages > 1) && ($this->current_page != 1)) { ?> <span class="pagination-prev">Prev</span> <?php } ?> <?php echo $this->current_page; ?> de <?php echo $this->total_pages; ?> <?php if(($this->total_pages > 1) && ($this->current_page != $this->total_pages)) { ?> <span class="pagination-next">Next</span> <?php } } ?>
        </span>
    </p>
</form>

<table width="100%" border="1">
    <thead>
        <tr>
            <th width="20%"></th>
            <th width="30%">Nome</th>
            <th width="20%">Email</th>
            <th width="10%">Telefone</th>
            <th width="15%">Cidade</th>
            <th width="2%">UF</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach($this->data as $row):?>
        <tr>
            <td align="center">
                <a class="edit-item" href="<?php echo HOST;?>adm/padrinhos/editar/<?php echo $row->id;?>" title="Editar">EDITAR</a>
                <a class="remove-item" href="<?php echo HOST;?>adm/padrinhos/excluir/<?php echo $row->id;?>" title="Remover">REMOVER</a>
            </td>
            <td><?php echo $row->nome;?></td>
            <td align="center"><?php echo $row->email;?></td>
            <td>
                <?php echo $row->tel_1;?>
                <?php if($row->tel_2): echo '<br>' . $row->tel_2; endif;?>
            </td>
            <td align="center"><?php echo $row->cidade;?></td>
            <td align="center"><?php echo $row->estado;?></td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>