<?php $meses = array (1 => "Janeiro", 2 => "Fevereiro", 3 => "Março", 4 => "Abril", 5 => "Maio", 6 => "Junho", 7 => "Julho", 8 => "Agosto", 9 => "Setembro", 10 => "Outubro", 11 => "Novembro", 12 => "Dezembro");?>

<h2>Prestação de contas</h2>
<p><a href="<?php echo HOST;?>adm/prestacao-de-contas/adicionar">Adicionar valores</a></p>
<div>
	<label for="select_year" style="width:130px;">Selecione o ano:</label>
	<select id="select_year" name="year">
		<?php for($i = date('Y'); $i >= 2005; $i--):?>
			<option value="<?php echo $i;?>" <?php echo ($this->current_year == $i) ? 'selected="selected"' : '';?>><?php echo $i;?></option>
		<?php endfor;?>
	</select>
</div>

<h4><?php echo $this->current_year;?></h4>
<?php if(is_array($this->data) and (sizeof($this->data) > 0)):?>
	<?php foreach($this->data as $month => $month_data):?>
		<?php $total = 0;?>
		<table width="100%" class="datagrid" border="1">
			<thead>
				<tr>
					<th colspan="3" style="text-align:left"><?php echo $meses[+$month];?></th>
				</tr>
				<tr>
                                        <th width="5%"></th>
					<td align="center" width="20%">Data</td>
					<td align="center" width="50%">Descrição</td>
					<td align="center" width="20%">Valor</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach($month_data as $row):
					$total += $row->amount;
					?>
					<tr>
                                                <td align="center">       
                                                    <a class="remove-item" href="<?php echo HOST;?>adm/prestacao-de-contas/remover/<?php echo $row->id;?>" title="Desativar"></a>
                                                </td>
						<td align="center"><?php echo date('d/m/Y', strtotime($row->date));?></td>
						<td><?php echo $row->description;?></td>
						<td align="right">
							<span style="float:left">R$</span>
							<span style="color:#<?php echo ($row->amount >= 0)?'050':'C00';?>"><?php echo number_format($row->amount, 2, ',', '.');?></span>
						</td>
					</tr>
				<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2" align="right">Subtotal:</td>
					<td align="right">
						<span style="float:left">R$</span>
						<span style="color:#<?php echo ($total >= 0)?'050':'C00';?>"><?php echo number_format($total, 2, ',', '.');?></span>
					</td>
				</tr>
			</tfoot>
		</table>
		<br /><br />
	<?php endforeach;?>
<?php else:?>
	<p>Não existem dados para o período selecionado</p>
<?php endif;?>

<script type="text/javascript">
	(function($){
		$("#select_year").change(function(){
			window.location.href = '<?php echo HOST;?>adm/prestacao-de-contas/?year=' + $(this).val();
		})
	}(jQuery));
</script>
