<h2><?php echo $this->title;?></h2>
<form action="<?php echo HOST;?>adm/destaques/salvar" method="post" enctype="multipart/form-data">
	<div>
		<label for="link">Link:</label>
		<input type="text" name="link" id="link" value="" maxlength="255" class="required" />
		<span>(Não é obrigatório)</span>
	</div>
	<div>
		<label for="picture">Imagem:</label>
		<input type="file" name="picture" id="picture" class="required" />
		<span>(Tamanho recomendado: 686x212)</span>
	</div>
	<div>
		<input type="submit" value="Salvar" />
	</div>
</form>