  <div id="home">
    <h1 class="h1">Novidades na versão (changelog):</h1>

    <h2>1.3.0</h2>
     <ul>
        <li><b>11/11/2017 admin</b> - Apontar página estática (alias).
            <p>Ao editar uma página, é possível adicionar manualmente a URL da versão
              estática, quando houver. Na listagem de páginas, esse alias
              aparecerá na coluna "Versão estática".</p>
        </li>
    </ul>

    <h2>1.2.0</h2>
     <ul>
        <li><b>08/10/2016 admin</b> - Funcionalidade de permissões.
            <p>Permissões de acesso aplicados ao sistema.</p>
        </li>
    </ul>

    <h2>1.1.0</h2>
    <ul>
        <li><b>29/08/2016 admin</b> - Adição de permissões na lista de voluntários.
            <p>Voluntários possuem 4 níveis de permissões.</p>
        </li>
    </ul>

</div>


<style>
    .h1{
        background:#2d4770;
        padding:10px 20px
    }
</style>
