<h2>Boletins</h2>
<p>
	<a href="<?php echo HOST;?>adm/boletins/adicionar">Adicionar boletim</a>
</p>
<table width="100%" border="1">
	<thead>
		<tr>
			<th width="13%"></th>
			<th>Título</th>
			<th>Chamada</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->data as $row):?>
			<tr>
				<td align="center">
					<a href="<?php echo HOST;?>adm/boletins/editar/<?php echo $row->id;?>" class="edit-item">EDITAR</a>
					<a href="<?php echo HOST;?>adm/boletins/remover/<?php echo $row->id;?>" class="remove-item">REMOVER</a>
				</td>
				<td><?php echo $row->title;?></td>
				<td><?php echo $row->heading;?></td>
			</tr>
		<?php endforeach;?>
	</tbody>
</table>