<h2><?php echo (isset($this->data->id)) ? 'Editar' : 'Adicionar';?> página</h2>
<form action="<?php echo HOST;?>adm/paginas/salvar" method="post">
	<?php if(isset($this->data->id)):?>
		<input type="hidden" name="page_id" value="<?php echo $this->data->id;?>" />
	<?php endif;?>
	<div>
		<label for="title">Título:</label>
		<input type="text" name="name" id="title" value="<?php echo $this->data->name;?>" style="width:655px;" maxlength="255" class="required"/>
	</div>
	<div>
		<label for="slug">URL:</label>
		<cite id="host_name"><?php echo HOST;?></cite>
		<input type="text" name="slug" id="slug" value="<?php echo $this->data->slug;?>" maxlength="255" class="required" />
	</div>
	<div>
		<label for="alias">Página estática:</label>
		<cite id="host_name"><?php echo HOST;?></cite>
		<input type="text" name="alias" id="alias" style="width:60%"
		value="<?php echo $this->data->alias;?>" maxlength="255" />
		<small style="display:block; padding-left:200px">Se existir uma página estática correspondente ou mais atualizada,
			insira a url</small>
	</div>
	<div>
		<textarea name="content"><?php echo str_replace('\r\n', '', stripslashes($this->data->content));?></textarea>
	</div>
	<div>
		<input type="submit" value="Salvar" />
	</div>
</form>
<script type="text/javascript">
	tinyMCE.init({
        mode : "textareas",
        theme : "advanced",
        plugins : "imagemanager,autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1: "save,|,bold,italic,underline,strikethrough,|,cut,copy,paste,pastetext,pasteword,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontsizeselect,cite,abbr,acronym,del,ins,|,bullist,numlist,|,sub,sup",
        theme_advanced_buttons2: "undo,redo,|,link,unlink,anchor,image,cleanup,code,insertimage,|,forecolor,backcolor,|,tablecontrols,|,print,fullscreen,|,hr,removeformat",
        theme_advanced_buttons3: "",
        theme_advanced_buttons4: "",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_resizing: false,

        // Skin options
        skin: "o2k7",
        skin_variant: "silver",
        relative_urls: false,
        content_css: "<?php echo HOST;?>templates/public/css/structure.css",
	});
</script>
<style>
	textarea{
		min-height: 500px;
	}

	label{
		width: 65px;
	}
</style>
<script type="text/javascript">
	$(document).ready(function(){
		$("#slug").width($("#title").width() - $("#host_name").width()-10);

		$("#title").bind('keyup keypress keydown blur', function(){
			var re = /[^a-z0-9]+/gi;
			var re2 = /^-*|-*$/g;

			$("#slug").val($(this).val().replace(re, '-').replace(re2, '').toLowerCase()).trigger("keypress");
		});

		$("form").bind('submit', function(){
			$("#loading-screen").fadeIn('fast');
		});

	});
</script>
