<h2><?php echo (isset($this->data->id)) ? 'Editar' : 'Adicionar';?> entrada - AUG na Mídia</h2>
<form enctype="multipart/form-data" action="<?php echo HOST;?>adm/aug-na-midia/salvar" method="post">
	<div id="new_picture">
		<?php if($this->data->picture == ''):?>
			<div style="background: url('<?php echo MEDIA_DIR.'images/adm/new_without-picture.png';?>') no-repeat center center;"></div>
		<?php else:?>
			<div style="background: url('<?php echo MEDIA_DIR.'uploads/pressreleases/'.$this->data->picture;?>') no-repeat center center;"></div>
		<?php endif;?>
	</div>
	<?php if(isset($this->data->id)):?>
		<input type="hidden" name="id" value="<?php echo $this->data->id;?>" />
	<?php endif;?>
	<div id="first-field">
		<label for="title">Título:</label>
		<input type="text" name="title" id="title" value="<?php echo $this->data->title;?>" style="width:400px;" maxlength="80" class="required" />
	</div>
	<div>
		<label for="heading">Chamada:</label>
		<input type="text" name="heading" id="heading" value="<?php echo $this->data->heading;?>" style="width:400px;" maxlength="160" class="required" />
	</div>
	<div>
		<label for="picture">Miniatura:</label>
		<input type="file" name="picture" id="picture" /><br/>
		<?php if($this->data->picture != ''):?>
			<span>Se quiser alterar a imagem atual, utilize o campo acima.</span>
		<?php endif;?>
	</div>
	<div id="content-container">
		<textarea name="content"><?php echo $this->data->content;?></textarea>
	</div>
	<div>
		<input type="submit" value="Salvar" />
	</div>
</form>
<script type="text/javascript">
	tinyMCE.init({
	    mode : "textareas",
	    theme : "advanced",
	    theme_advanced_buttons1 : "save,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
	    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,insertimage,cleanup,|,forecolor,backcolor,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,code",
	    theme_advanced_buttons3 : "",
	    theme_advanced_toolbar_location : "top",
	    theme_advanced_toolbar_align : "left",
	    theme_advanced_statusbar_location : "bottom",
	    content_css : "<?php echo HOST;?>templates/public/css/structure.css",
	    plugins: "imagemanager,inlinepopups",
	    skin: "o2k7",
        skin_variant: "silver",
        relative_urls: false,
	});
</script>
<style>
	textarea{
		min-height: 380px;
	}
	
	#content-container{
		padding-top: 60px;
	}
	
	label{
		width: 280px;
	}
	
	#first-field{
		padding-top: 40px;
	}
	
	#new_picture{
		display: block;
		position: absolute;
		height: 200px;
		width: 200px;
		background: #f0f0ee;
		border: 1px solid #cccccc;
		padding: 5px;
		border-radius: 5px;
		-moz-border-radius: 5px;
		-webkit-border-radius: 5px;
	}
	
	#new_picture div{
		display: block;
		background: #C00;
		height: 183px;
		width: 200px
	}
	
	form div span{
		padding-left: 197px;
	}
</style>