<link rel="stylesheet" href="/css/admin.fila.css">
<h1 class="h1"><?php echo $this->title;?></h1>

<div class="row">
  <h2 class="col s12">Lista de espera de <span id="cat-name"><?php echo $this->data[0]->cat_name;?></span></h2>


  <section class="col s12">
    <form class="row" action="index.html" method="post" id="petz-notification" style="display:none">
      <fieldset class="rel">

        <div class="row m-b-0">
          <div class="col s10">
            <legend class=" legend">Enviar email e mudar status</legend>
          </div>

          <div class="col s2">
            <button type="button" class="close">X</button>
          </div>
        </div>

        <div class="row">
          <input type="hidden" name="current_id" id="current_id" value="">
        <div class="col s4">
          <label for="current_user">Para</label>
          <input type="text" name="current_user" id="current_user" value="">
        </div>

        <div class="col s4">
          <label for="current_email">E-mail</label>
          <input type="text" name="current_email" id="current_email" value="">
        </div>

        <div class="col s4">
          <label for="tipo">Tipo de mensagem</label>
          <select id="tipo" name="tipo" disabled="disabled">
            <option value="APPROVED">Cadastro aprovado</option>
            <option value="REJECTED">Cadastro rejeitado</option>
          </select>
        </div>

        <div class="col s12">
          <label for="notify">Deseja notificar o usuário por email?</label>
          <select name="notify" id="notify">
            <option value="1">Sim</option>
            <option value="0">Não</option>
          </select>
        </div>

        <div class="col s12" id="email_box">
          <label for="msg">Conteúdo do email</label>
          <textarea id="msg" name="msg"></textarea>
        </div>

        <div class="col s12">
          <p class="alert alert-warning"><strong>Atenção: </strong> Só é possível aprovar um usuário por vez.
            Submeter este formulário implicará na mudança
          de status em cadeia: todos os demais usuários que não estiverem marcados
          como REJEITADOS serão recolocados na fila de espera, mas não serão notificados.</p>
        </div>

        <div class="col s12">
          <button type="submit" name="button" class="submit">Enviar</button>
        </div>
        </div>
      </fieldset>
    </form>
  </section>


  <div class="col s4 text-center">
    <!-- <img src="<?php echo MEDIA_DIR;?>uploads/cats/<?= $this->data[0]->cat_picture;?>" class="m-b-10" /> -->
    <img src="http://www.adoteumgatinho.com.br/media/uploads/cats/<?= $this->data[0]->cat_picture;?>" class="m-b-10" />
    <div class="col s6">
      <a href="<?= HOST?>/detalhes-gato/<?= $this->data[0]->cat_id;?>/<?= $this->data[0]->cat_name;?>" class="p-05 ui-button ui-widget ui-state-default ui-corner-all">Ver perfil</a>
    </div>
    <div class="col s6">
      <a href="<?= HOST?>/adm/gatos/editar/<?= $this->data[0]->cat_id;?>" class="p-05 ui-button ui-widget ui-state-default ui-corner-all">Editar perfil</a>
    </div>


  </div>
  <div class="col s8">
    <table class="queue_list">
      <thead>
        <tr>
          <th>Candidatos</th>
          <th>Status</th>
          <th>Entrada</th>
        </tr>
      </thead>
      <tbody>
        <?php //if(isset($this->data) and count($this->data) > 0) {?>
          <?php foreach($this->data as $row) {?>
            <tr data-id="<?= $row->queue_id ?>" data-user="<?= $row->user_id ?>">
              <td>
                <a href="#-<?php echo HOST;?>"><?= $row->user_name ?></a><br>
                <small>
                  <?= $row->user_email ?> <br>
                  <?= $row->user_tel ?>
                </small>
              </td>
              <td>
                <select class="statuses" name="fila-<?= $row->queue_id ?>"  data-id="<?= $row->queue_id ?>" data-name="<?= $row->user_name ?>" data-email="<?= strtolower($row->user_email) ?>">
                  <option value="" <?= (isset($row->status) < 3) ? 'selected="selected"' : '' ?>></option>
                  <option value="WAIT" <?= ($row->status == 'WAIT') ? 'selected="selected"' : '' ?>>Aguardando</option>
                  <option value="APPROVED" <?= ($row->status == 'APPROVED') ? 'selected="selected"' : '' ?>>Aprovado</option>
                  <option value="REJECTED" <?= ($row->status == 'REJECTED') ? 'selected="selected"' : '' ?>>Rejeitado</option>
                </select>
              </td>
              <td>
                <?php
                $date = new DateTime($row->register_date);
                echo $date->format('d/m/Y') .'<br><small>às '.  $date->format('H:i:s') . '</small>'; ?>
              </td>

            </tr>
          <?php } ?>
        <?php //} ?>
      </tbody>
    </table>
  </div>
</div>

<script src="/js/admin.fila.js"></script>
