<h1 class="h1"><?php echo $this->title;?></h1>

<style media="screen">
.h1{
  color: #2d4770;
  text-shadow: none
}
img {
  max-width: 100%;
  height: auto;
}
.row {
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 20px;
    float: left;
}
.row .col {
  margin-left: auto;
  left: auto;
  right: auto;
  float: left;
}
.row .col.s1 {
    width: 8.3333333333%;
}
.row .col.s2 {
    width: 16.6666666667%;
}
.row .col.s3 {
    width: 25%;
}
.row .col.s4 {
    width: 33.3333333333%;
}
.row .col.s5 {
    width: 41.6666666667%;
}
.row .col.s6 {
    width: 50%;
}
.row .col.s7 {
    width: 58.3333333333%;
}
.row .col.s8 {
    width: 66.6666666667%;
}
.row .col.s9 {
    width: 75%;
}
.row .col.s10 {
    width: 83.3333333333%;
}
.row .col.s11 {
    width: 91.6666666667%;
}
.row .col.s12 {
    width: 100%;
}

.queue_list{
  width: 100%;
}

.queue_list tr{
  border-bottom: 1px #eee solid
}

.queue_list td, .queue_list th {
  padding:5px 15px;
}

.m-b-10{
  margin-bottom: 1.0rem;
}

.p-05{
  padding: .5rem;
}
.text-center {
  text-align: center;
}
</style>


<div class="row">
  <h2>Lista de espera de <?php echo $this->data[0]->cat_name;?></h2>
  <div class="col s4 text-center">
    <!-- <img src="<?php echo MEDIA_DIR;?>uploads/cats/<?= $this->data[0]->cat_picture;?>" class="m-b-10" /> -->
    <img src="http://www.adoteumgatinho.com.br/media/uploads/cats/<?= $this->data[0]->cat_picture;?>" class="m-b-10" />
    <div class="col s6">
      <a href="<?= HOST?>/detalhes-gato/<?= $this->data[0]->cat_id;?>/<?= $this->data[0]->cat_name;?>" class="p-05 ui-button ui-widget ui-state-default ui-corner-all">Ver perfil</a>
    </div>
    <div class="col s6">
      <a href="<?= HOST?>/adm/gatos/editar/<?= $this->data[0]->cat_id;?>" class="p-05 ui-button ui-widget ui-state-default ui-corner-all">Editar perfil</a>
    </div>


  </div>
  <div class="col s8">
    <table class="queue_list">
      <thead>
        <tr>
          <th>Candidatos</th>
          <th>Status</th>
          <th>Entrada</th>
        </tr>
      </thead>
      <tbody>
        <?php //if(isset($this->data) and count($this->data) > 0) {?>
          <?php foreach($this->data as $row) {?>
            <tr data-id="<?= $row->queue_id ?>">
              <td>
                <a href="<?php echo HOST;?>"><?= $row->user_name ?></a><br>
                <small>
                  <?= $row->user_email ?> <br>
                  <?= $row->user_tel ?>
                </small>
              </td>
              <td>
                <select class="" name="fila-<?= $row->queue_id ?>"  data-id="<?= $row->queue_id ?>">
                  <option value=""></option>
                  <option value="WAIT" <?= ($row->status == 'WAIT') ? 'selected="selected"' : '' ?>>Aguardando</option>
                  <option value="APPROVED" <?= ($row->status == 'APPROVED') ? 'selected="selected"' : '' ?>>Aprovado</option>
                  <option value="REJECTED" <?= ($row->status == 'REJECTED') ? 'selected="selected"' : '' ?>>Rejeitado</option>
                </select>
              </td>
              <td>
                <?php
                $date = new DateTime($row->register_date);
                echo $date->format('d/m/Y') .'<br><small>às '.  $date->format('H:i:s') . '</small>'; ?>
              </td>
            </tr>
          <?php } ?>
        <?php //} ?>
      </tbody>
    </table>
  </div>
</div>
