<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

        <title><?php echo SITE_NAME;?></title>

        <script type="text/javascript">var HOST="<?php echo HOST;?>";</script>
        <script type="text/javascript" src="<?php echo MEDIA_DIR;?>tiny_mce/tiny_mce.js"></script>
        <script type="text/javascript" src="<?php echo MEDIA_DIR;?>tiny_mce/langs/pt.js"></script>
        <script type="text/javascript" src="<?php echo MEDIA_DIR;?>scripts/jquery.js"></script>
        <script type="text/javascript" src="<?php echo MEDIA_DIR;?>scripts/jquery.lazyload.js"></script>
        <script type="text/javascript" src="<?php echo MEDIA_DIR;?>scripts/jquery-ui.js"></script>
        <script type="text/javascript" src="<?php echo MEDIA_DIR;?>scripts/jquery.mask.js"></script>
        <script type="text/javascript" src="<?php echo MEDIA_DIR;?>scripts/jquery.validate.js"></script>
        <script type="text/javascript" src="<?php echo MEDIA_DIR;?>fancybox/jquery.fancybox-1.3.4.js"></script>

        <link href="<?php echo MEDIA_DIR;?>styles/adm/admin.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo MEDIA_DIR;?>styles/adm/jquery.tipsy.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo MEDIA_DIR;?>styles/jquery-ui/jquery-ui-1.8.17.custom.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo MEDIA_DIR;?>fancybox/jquery.fancybox-1.3.4.css" rel="stylesheet" type="text/css" />
    </head>

<body>

    <div id="loading-screen">
        <div id="loader-background"></div>
        <div id="loader-message">
            <h2>Carregando</h2>
            <h3>Aguarde</h3>
            <img src="<?php echo MEDIA_DIR;?>images/adm/loading.gif" alt="Carregando..." />
        </div>
    </div>

    <div id="_container">
        <div id="_topo">
            <div id="_titulo">
                    <h1><?php echo SITE_NAME;?></h1>
            </div>
            <div id="sair">
                    <a id="bot_sair" href="<?php echo HOST;?>adm/logout/">Sair</a>
            </div>
        </div>

        <div id="menu_esquerda">
            <a class="menu_item" href="<?php echo HOST;?>adm/">
                <div class="menu_icon" id="home_menu"></div>
                <span>Home</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/padrinhos">
                <div class="menu_icon" id="godfather_menu"></div>
                <span>Padrinhos</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/empresas">
                <div class="menu_icon" id="company_menu"></div>
                <span>Empresas parceiras</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/gatos/all">
                <div class="menu_icon" id="cats_menu"></div>
                <span>Gatos</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/gatos/adicionar">
                <div class="sub_menu_icon"></div>
                <span>Adicionar</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/gatos/para-adocao">
                <div class="sub_menu_icon"></div>
                <span>P/ Adoção</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/gatos/adotados">
                <div class="sub_menu_icon"></div>
                <span>Adotados</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/gatos/reservas">
                <div class="sub_menu_icon"></div>
                <span>Reservados</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/gatos/para-apadrinhamento">
                <div class="sub_menu_icon"></div>
                <span>P/ Apadrinhamento</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/gatos/reordenar-gatos">
                <div class="sub_menu_icon" id="reorder-cats-menu"></div>
                <span>Gatos</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/gatos/reordenar-apadrinhados">
                <div class="sub_menu_icon" id="reorder-cats-menu"></div>
                <span>Apadrinhados</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/gatos/desativados">
                <div class="sub_menu_icon"></div>
                <span>Desativados</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/paginas/">
                <div class="menu_icon" id="pages_menu"></div>
                <span>Páginas</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/paginas/adicionar">
                <div class="sub_menu_icon"></div>
                <span>Adicionar</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/destaques/">
                <div class="menu_icon" id="billboard_menu"></div>
                <span>Destaques</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/newsletter/">
                <div class="menu_icon" id="newsletter_menu"></div>
                <span>Newsletter</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/newsletter/extrair-relatorio" target="_blank">
                <div class="sub_menu_icon"></div>
                <span>Extrair relatório</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/depoimentos/">
                <div class="menu_icon" id="testimonials_menu"></div>
                <span>Depoimentos</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/depoimentos/adicionar">
                <div class="sub_menu_icon"></div>
                <span>Adicionar</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/materias/">
                <div class="menu_icon" id="news_menu"></div>
                <span>Matérias</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/materias/adicionar">
                <div class="sub_menu_icon"></div>
                <span>Adicionar</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/aug-na-midia/">
                <div class="menu_icon" id="aug-na-midia-menu"></div>
                <span>AUG na Mídia</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/aug-na-midia/adicionar">
                <div class="sub_menu_icon"></div>
                <span>Adicionar</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/boletins/">
                <div class="menu_icon" id="boletins-menu"></div>
                <span>Boletins</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/boletins/adicionar">
                <div class="sub_menu_icon"></div>
                <span>Adicionar</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/prestacao-de-contas">
                <div class="menu_icon" id="accounting_menu"></div>
                <span>Prestação de contas</span>
            </a>

            <a class="menu_item" href="<?php echo HOST;?>adm/usuarios/">
                <div class="menu_icon" id="users_menu"></div>
                <span>Voluntários</span>
            </a>
        </div>

        <div id="content">
            <?php $this->loadViewContent();?>
        </div>
    </div>
</body>
<script type="text/javascript">
(function($){
    $(document).ready(function(){

        $("img.lazy-load").lazyload();

        //$("form").validate();

        $("input:text[maxlength]").each(function(){
                var $ipt = $(this);
            var $counter = $("<cite>").html($ipt.attr("maxlength")).addClass("char-counter");
            $counter.insertAfter($ipt);

            $ipt.bind("keyup keypress keydown", function(evt){
                    $counter.html($ipt.attr("maxlength") - $ipt.val().length);
            });
        });

        $("#menu_esquerda a.menu_item").each(function(){
            if(location.href.toString().indexOf($(this).attr("href")) != -1){
                    $(".active_menu_item").removeClass("active_menu_item");
                    $(this).addClass("active_menu_item");
            }
        });

        $(".fancybox").fancybox();
        $("button, input:submit").button();

        $(".remove-item").click(function(evt){
            var $el = $(this);

            evt.preventDefault();
            evt.stopPropagation();

            $("<div><p>Tem certeza que deseja apagar este registro?</p></div>").dialog({
                title: "Confirmação",
                buttons: {
                    Ok: function(){
                            window.location.href = $el.attr("href");
                    },
                    Cancelar: function(){
                            $(this).dialog("close");
                    }
                },
                modal: true
            });
        });
    });
}(jQuery));
</script>

</html>
