<!doctype html>
<html>
	<head>
		<title><?php echo SITE_NAME;?></title>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
		<link href="<?php echo MEDIA_DIR;?>styles/adm/login.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<div id="login-wrapper">
			<form action="<?php echo HOST;?>adm/processar-login" method="POST">
				<div>
					<img src="<?php echo HOST;?>templates/public/css/images/logo.png" />
				</div>
				<div>
					<div>
						<label for="username">Usuário</label>
						<input type="text" id="username" name="username" />
					</div>
					<div>
						<label for="password">Senha</label>
						<input type="password" id="password" name="password" />
					</div>
					<div>
						<input type="submit" value="Entrar" />
					</div>
				</div>
			</form>
		</div>
	</body>
</html>
