<!DOCTYPE html>
<html lang="pt">

<!-- # # # # # # # # # # # #
    NOVO INDEX
 # # # # # # # # # # # # # # # #-->
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

		<link rel="shortcut icon" href="<?php echo HOST;?>favicon.png" type="image/png" />
		<title><?php echo $this->og->title;?></title>


		<?php if($this->og):?>
			<meta property="og:title" content="<?php echo $this->og->title;?>" />
			<meta property="og:description" content="<?php echo strip_tags($this->og->description);?>" />
			<meta property="og:image" content="<?php echo $this->og->img;?>" />
			<meta property="og:url" content="<?php echo HOST.URI;?>" />
			<meta property="og:type" content="website" />
		<?php endif;?>
        <link rel="stylesheet" href="<?php echo HOST;?>css/screen.css" />
       <script src="<?php echo HOST;?>js/jquery.min.js"></script>
	</head>
	<body>
<!--
		<div id="fb-root"></div>
                <script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=281099021901939";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
-->


            <!-- # # # # # # # # # # # # # #
    Header
# # # # # # # # # # # # # # -->
    <header class="row m-b-0" id="head">
        <div class="col s4 m6 l7 offset-l1">
            <a id="logo" href="<?php echo HOST;?>">
                <div class="logo-icon"></div>
                <div class="logotype hide-on-small-and-down" title="<?php echo SITE_NAME;?>"></div>
            </a>
        </div>

        <div class="col s8 m6 l4">
<!--           Ícones-->
            <ul class="col s10 nav right upper" id="nav-menu">
               <li class="hide-on-med-and-up top_search" id="top_search">
                   <form class="relative search_container"  action="<?php echo HOST;?>buscar" method="get">
                    <input type="search" name="q" id="busca" class="col s9 search_field">
                    <button type="submit" class="col s3 float_submit" id="botao_busca"><i class="icon-grey ic-zoom m-l-10"></i></button>
                </form>
               </li>

                <li class="relative right m-t-3" id="open_menu"><a href="#" class="grey-text"><i class="icon-grey ic-list"></i> <span class="hide-on-med-and-down">Menu</span></a>
                    <menu id="menu" class="right">
                        <ul>
                            <li><a href="<?php echo HOST;?>sobre">A ONG</a></li>
														<li><a href="<?php echo HOST;?>reforma">Reforma</a></li>
                            <li><a href="<?php echo HOST;?>quero-adotar">Quero adotar</a></li>
                            <li><a href="<?php echo HOST;?>adocoes-especiais">Adoções especiais</a></li>
                            <li><a href="<?php echo HOST;?>quero-ajudar-a-aug">Quero ajudar</a></li>
                            <li><a href="<?php echo HOST;?>apadrinhamento">Apadrinhamento</a></li>
                            <li><a href="<?php echo HOST;?>resgate">Resgate</a></li>
                            <li><a href="<?php echo HOST;?>gatos-adotados">Gatos adotados</a></li>
                            <li><a href="<?php echo HOST;?>prestacao-de-contas/contas?year=2016">Prestação de contas</a></li>
                            <li><a href="<?php echo HOST;?>aug-na-midia">Na mídia</a></li>
                            <li><a href="<?php echo HOST;?>boletins">Boletim AUG</a></li>
                            <li><a href="http://www.auglojinha.com.br/" target="_blank">Lojinha</a></li>
                            <li><a href="<?php echo HOST;?>faq">FAQ</a></li>
                            <li><a href="<?php echo HOST;?>parceiros-e-links">Parceiros</a></li>
                            <li><a href="<?php echo HOST;?>contato">Contato</a></li>
                          </ul>
                      </menu>
                </li>
                <li class="hide-on-med-and-down right"><a href="<?php echo HOST;?>contato" class="icon-grey ic-email"></a></li>
                <li class="hide-on-med-and-down right"><a href="#top_search" class="icon-grey ic-zoom" id="open_search"></a></li>
            </ul>
            <ul class="col s1 push-s1 nav m-t-3 m-b-3 hide-on-med-and-down" style="zoom: 80%;">
                <li class="right">
                <a href="http://www.facebook.com/adoteumgatinho" target="_blank" class="icon-grey ic-facebook"></a></li>
                <li class="right">
                <a href="https://www.instagram.com/adoteumgatinho/?hl=pt-br" target="_blank" class="icon-grey ic-instagram"></a></li>
                <li class="right">
                <a href="http://www.twitter.com/adoteumgatinho" class="icon-grey ic-twitter" target="_blank"></a> </li>
            </ul>
        </div>
    </header>

<!-- # # # # # # # # # # # # # #
    Elementos mobile
# # # # # # # # # # # # # # -->
<nav class="hidden_menu hide-med-and-up">

   <form class="row relative" action="<?php echo HOST;?>buscar" method="get">
     <div class="col s1">
         <button type="button" id="hide_menu"><i class="icon-white ic-arrow-right"></i></button>
     </div>
     <fieldset class="mob_search col s9 offset-s1">
                <input type="search" name="q" placeholder="busca por termo" class="search_field">
                <button type="submit" class="left"><i class="icon-white ic-zoom"></i></button>
        </fieldset>
   </form>
    <ul>
        <li><a href="<?php echo HOST;?>sobre">A ONG</a></li>
				<li><a href="<?php echo HOST;?>reforma">Reforma</a></li>
        <li><a href="#">Quero adotar</a>
            <ul>

                <li><a href="<?php echo HOST;?>gatinhos-para-adocao" class="aug_blue">Gatinhos para adoção</a></li>
                <li><a href="<?php echo HOST;?>adocoes-especiais" class="aug_blue">Adoções especiais</a></li>
                <li><a href="<?php echo HOST;?>como-adotar-um-gatinho" class="aug_blue">Como faço para adotar um gatinho?</a></li>
                <li><a href="<?php echo HOST;?>politica-de-adocao-aug" class="aug_blue">Política de adoção</a></li>
                <li><a href="<?php echo HOST;?>depoimentos" class="aug_blue">Depoimentos</a></li>
                <li><a href="<?php echo HOST;?>quero-adotar#Informacoes-importantes" class="aug_blue">Informações importantes</a></li>
            </ul>
        </li>
        <li><a href="<?php echo HOST;?>quero-ajudar-a-aug">Quero ajudar</a></li>
        <li><a href="<?php echo HOST;?>apadrinhamento">Apadrinhamento</a></li>
        <li><a href="<?php echo HOST;?>resgate">Resgate</a></li>
        <li><a href="<?php echo HOST;?>gatos-adotados">Gatos adotados</a></li>
        <li><a href="<?php echo HOST;?>prestacao-de-contas/contas?year=2016">Prestação de contas</a></li>
        <li><a href="<?php echo HOST;?>aug-na-midia">Na mídia</a></li>
        <li><a href="<?php echo HOST;?>boletins">Boletim AUG</a></li>
        <li><a href="http://www.auglojinha.com.br/" target="_blank">Lojinha</a></li>
        <li><a href="<?php echo HOST;?>faq">FAQ</a></li>
        <li><a href="<?php echo HOST;?>parceiros-e-links">Parceiros</a></li>
        <li><a href="<?php echo HOST;?>contato">Contato</a></li>
    </ul>
</nav>


    <!-- # # # # # # # # # # # # # #
    Content
# # # # # # # # # # # # # # -->
   <div class="aug_grey_bg m-b-0">
      <?php $this->loadViewContent();?>
</div>



<!-- # # # # # # # # # # # # # #
    Footer
# # # # # # # # # # # # # # -->
<footer id="footer">
   <section class="row grey m-b-0">
<!--       bloco 1-->
        <div class="col s12 m6 l3 offset-l1 hide-on-small-only">
            <strong>Adote um gatinho</strong>
            <p class="block-box">O Adote um Gatinho busca lares para gatos encontrados abandonados na Grande São Paulo e também trabalha para conscientizar as pessoas sobre a importância da castração e posse responsável.</p>
        </div>


<!--bloco 2-->
       <menu class="col s12 m6 l4 hide-on-small-only">
            <strong>Menu</strong>
            <div class="col s6">
                <ul class="block-box">
                    <li><a href="<?php echo HOST;?>sobre">A ONG</a></li>
                    <li><a href="<?php echo HOST;?>quero-adotar">Quero adotar</a></li>
                    <li><a href="<?php echo HOST;?>quero-ajudar-a-aug">Quero ajudar</a></li>
                    <li><a href="<?php echo HOST;?>resgate">Resgate</a></li>
                    <li><a href="<?php echo HOST;?>gatos-adotados">Gatos adotados</a></li>
                    <li><a href="<?php echo HOST;?>prestacao-de-contas/contas?year=2016">Prestação de contas</a></li>
                </ul>
            </div>

            <div class="col s4">
                <ul class="block-box">
                    <li><a href="<?php echo HOST;?>aug-na-midia">Na mídia</a></li>
                    <li><a href="<?php echo HOST;?>boletins">Boletim AUG</a></li>
                    <li><a href="http://www.auglojinha.com.br/" target="_blank">Lojinha</a></li>
                    <li><a href="<?php echo HOST;?>faq">FAQ</a></li>
                    <li><a href="<?php echo HOST;?>parceiros-e-links">Parceiros</a></li>
                    <li><a href="<?php echo HOST;?>contato">Contato</a></li>
                </ul>
            </div>
        </menu>


<!--Bloco 3-->
        <fieldset class="col s12 m12 l4">
           <strong class="hide-on-small-only">Siga o AUG</strong>
            <nav id="redes" class="col s12">
                <a href="http://www.facebook.com/adoteumgatinho" target="_blank" class="icon-white ic-facebook"></a>
                <a href="https://www.instagram.com/adoteumgatinho/?hl=pt-br" target="_blank" class="icon-white ic-instagram"></a>
                <a href="http://www.twitter.com/adoteumgatinho" class="icon-white ic-twitter" target="_blank"></a>
            </nav>

            <strong>Receba nossa newsletter</strong>
            <form class="block-box" method="post" id="newsletter-signup-form" action="<?php echo HOST;?>cadastre-se/confirmar">
                <div class="col s12 clear">
                    <input type="text" name="name" id="name" placeholder="Nome">
                    <input type="email"  name="email" id="email" placeholder="E-mail">
                    <button type="submit" class="icon-white ic-arrow-right"></button>
                </div>
            </form>
        </fieldset>
    </section>



    <div class="row upper grey darken-2 m-b-0 cancel-margin-40">
        <div class="col s8">
            2013 ~ <?php echo date("Y"); ?> - Adote um gatinho. Todos os direitos reservados.
        </div>
        <div class="col s4">
            <a href="http://www.elementodesign.com.br" target="_blank">Design by Elemento</a>
        </div>
    </div>
</footer>
     <style>
    table#Table_01, #Table_01 img{
        width: 100%!important;
    height:auto!important}
</style>


        <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-3360136-1']);
        _gaq.push(['_trackPageview']);

        (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

        </script>

<script src="<?php echo HOST;?>js/bin/materialize.min.js"></script>
<script src="<?php echo HOST;?>js/_main.min.js"></script>
</body>
</html>
