<?php 
$breadColor = 'orange';
$breadPaths = array();
$lastPath = 'Sobre';
include('top.phtml'); 

?>  
<div class="aug_grey_bg">
        <div class="row" style="background-color: #d1d1d1;">
            <div class="row container-large m-b-0">
                <div class="video-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/R_w3UDt06YI" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
        <div class="row container m-b-0">
            <div class="col s12">
                <h1 class="col s12 h1 bold upper aug_orange">Quem somos</h1>
                <p class="text_10 m-t-10">O Adote um Gatinho surgiu em janeiro de 2003, sem querer, quando as fundadoras Susan Yamamoto e Juliana Bussab se voluntriaram para ajudar alguns gatos de um parque, em São Paulo, e se conheceram. Elas perceberam que tinham algo que as unia: a vontade sem fim de ajudar os animais abandonados.</p>
                <p class="text_10 m-t-10">Por alguns anos elas permaneceram sozinhas, levando os gatinhos para suas casas, batalhando doações e lares para eles. Foram anos difíceis, sem estrutura, sem dinheiro mas com muita garra. Até que em 2006 um grupo de pessoas que acompanhava o trabalho das duas se ofereceu para unir forças e trabalhar como voluntários. No ano seguinte, o “grupo Adote um Gatinho" se oficializou como a "ONG Adote um Gatinho".</p>
                <p class="text_10 m-t-10">Apesar de a AUG hoje ser considerada a maior ONG de resgate e doação de gatos do Brasil, ainda lutamos com dificuldade para sustentar os nossos animais e continuar resgatando outros das ruas. Em todos estes anos de existência ainda não conseguimos o nosso primeiro patrocínio e vivemos graças à ajuda de muita gente bacana, pessoas comuns, que apreciam o que a gente faz.</p>
                <p class="text_10 m-t-10">Na medida do possível, a gente procura ajudar o maior número de bichinhos. Todos passam por consulta veterinária e são tratados, vermifugados, vacinados e castrados antes de serem colocados para adoção.</p>
                <p class="text_10 m-t-10">Não parece muito difícil, né? Mas é! Porque cuidar de gatos não é só fazer cafuné e dar ração. Os animais chegam da rua judiados, subnutridos, amedrontados, deprimidos e doentes. Muitos não comem sozinhos ou precisam de medicação várias vezes ao dia.</p>
                <p class="text_10 m-t-10">Às vezes desanimamos, choramos, enfiamos a cara no travesseiro porque é muito difícil lidar com o sofrimento de seres indefesos e com o pior lado do ser humano - aquele que abandona, que finge que não vê, que prefere largar animais à própria sorte ou empurrar "o problema" pra gente. Mas olhamos para trás, enxugamos as lágrimas, respiramos fundo… vemos que já conseguimos encaminhar milhares de gatinhos, que hoje dormem quentinhos na cama com seus donos, e juntamos forças para seguir em frente.</p>
                <p class="text_10 m-t-10">Valeu e está valendo a pena!</p>

                <h2 class="text_20 bold upper aug_orange">NOSSO OBJETIVO</h2>

                <p class="text_10 m-t-10">O Adote um Gatinho busca lares para gatos encontrados abandonados na Grande São Paulo e também trabalha para conscientizar as pessoas sobre a importância da castração e posse responsável. Gatas dão cria até 4 vezes por ano, a partir dos 5 ou 6 meses. Com a castração, reduzimos a quantidade de animais passando frio, fome e sendo maltratados nas ruas.</p>
                <p class="text_10 m-t-10">O Adote um Gatinho está em São Paulo - SP. Os animais ficam abrigados na nossa sede e também nas casas dos voluntários.</p>
                <p class="text_10 m-t-10">NÃO recolhemos ou resgatamos animais que estejam além de nossa capacidade. Hoje o AUG abriga 400 gatos.</p>
                <p class="text_10 m-t-10">O Adote um Gatinho é formado por:</p>
            </div>
            <div class="col s12">
                <ul class="collection">
                    <li class="collection-item col s12 m6" style="line-height: 32px">
                        <a href="mailto:juliana@adoteumgatinho.org.br">
                              <!-- <img src="http://lorempixel.com/50/50/cats/1" alt="" class="circle"> -->
                              <span class="title bold upper aug_orange truncate">Juliana Bussab</span>
                              <p class="aug_black truncate"><span class="bold">Fundadora</span><br>
                                 juliana@adoteumgatinho.org.br
                              </p> 
                        </a>
                    </li>
                   

                    <li class="collection-item col s12 m6" style="line-height: 32px">    
                        <a href="mailto:susan@adoteumgatinho.org.br">                
                          <!-- <img src="http://lorempixel.com/50/50/cats/3" alt="" class="circle"> -->
                          <span class="title bold upper aug_orange truncate">Susan Yamamoto</span>
                          <p class="aug_black truncate"><span class="bold">Fundadora</span><br>
                             susan@adoteumgatinho.org.br
                          </p>
                         </a>
                   </li>
                </ul>


            </div>
            <div class="col s12 l6">
                <ul class="collection">
                <li class="collection-item" style="line-height: 32px">    
                        <a href="mailto:adocoes@adoteumgatinho.org.br">                
                          <!-- <img src="http://lorempixel.com/50/50/cats/4" alt="" class="circle"> -->
                          <span class="title bold upper aug_orange truncate">Andréa Moraes</span>
                          <p class="aug_black truncate"><span class="bold">Coordenação Abrigo e Visitas</span><br>
                             adocoes@adoteumgatinho.org.br
                          </p>
                         </a>
                   </li>
                   <li class="collection-item" style="line-height: 32px">    
                        <a href="mailto:denise@adoteumgatinho.org.br">                
                          <!-- <img src="http://lorempixel.com/50/50/cats/7" alt="" class="circle"> -->
                          <span class="title bold upper aug_orange truncate">Denise Granja</span>
                          <p class="aug_black truncate"><span class="bold">Revisão de textos</span><br>
                            denise@adoteumgatinho.org.br
                          </p>
                         </a>
                   </li>
                    <li class="collection-item" style="line-height: 32px">
                        <a href="mailto:hellen@adoteumgatinho.org.br">
                              <!-- <img src="http://lorempixel.com/50/50/cats/8" alt="" class="circle"> -->
                              <span class="title bold upper aug_orange truncate">Hellen Domingues</span>
                              <p class="aug_black truncate"><span class="bold">Departamento pessoal</span><br>
                                 hellen@adoteumgatinho.org.br
                              </p> 
                        </a>
                    </li> 
                    <li class="collection-item" style="line-height: 32px">    
                        <a href="mailto:luciana@imagemcom.com.br">                
                          <!-- <img src="http://lorempixel.com/50/50/cats/10" alt="" class="circle"> -->
                          <span class="title bold upper aug_orange truncate">Luciana Siqueira</span>
                          <p class="aug_black truncate"><span class="bold">Assessoria de imprensa</span><br>
                             luciana@imagemcom.com.br
                          </p>
                         </a>
                   </li>
                     <li class="collection-item" style="line-height: 32px">    
                        <a href="mailto:lucy@adoteumgatinho.org.br">                
                          <!-- <img src="http://lorempixel.com/50/50/cats/3" alt="" class="circle"> -->
                          <span class="title bold upper aug_orange truncate">Lucy Cardia</span>
                          <p class="aug_black truncate"><span class="bold">Parcerias exclusivas Bazar de Natal e Arraial</span><br>
                             lucy@adoteumgatinho.org.br
                          </p>
                         </a>
                   </li>
                    <li class="collection-item" style="line-height: 32px">
                        <a href="mailto:resgates@adoteumgatinho.org.br">
                              <!-- <img src="http://lorempixel.com/50/50/cats/1" alt="" class="circle"> -->
                              <span class="title bold upper aug_orange truncate">Priscila Garcia</span>
                              <p class="aug_black truncate"><span class="bold">Atendimento a pedidos de ajuda e resgates</span><br>
                                 resgates@adoteumgatinho.org.br
                              </p> 
                        </a>
                    </li>

                    
                </ul>
            </div>
            <div class="col s12 l6">
                <ul class="collection">
                  <li class="collection-item" style="line-height: 32px">    
                      <a href="mailto:andrea@adoteumgatinho.org.br">                
                        <!-- <img src="http://lorempixel.com/50/50/cats/6" alt="" class="circle"> -->
                        <span class="title bold upper aug_orange truncate">Andréa Moraes</span>
                        <p class="aug_black truncate"><span class="bold">Parcerias online e eventos</span><br>
                           andrea@adoteumgatinho.org.br
                        </p>
                       </a>
                  </li>
                  <li class="collection-item" style="line-height: 32px; height: 76px;">
                    <!-- <img src="http://lorempixel.com/50/50/cats/10" alt="" class="circle"> -->
                    <span class="title bold upper aug_orange">Karla M. Ruivo</span>
                    <p class="aug_black truncate"><span class="bold">Organização de doações, estoque e produtos</span>
                    </p> 
                  </li>
                  <li class="collection-item" style="line-height: 32px">    
                    <a href="mailto:juridico@adoteumgatinho.org.br">                
                      <!-- <img src="http://lorempixel.com/50/50/cats/9" alt="" class="circle"> -->
                      <span class="title bold upper aug_orange truncate">Rodrigo Carneiro</span>
                      <p class="aug_black truncate"><span class="bold">Jurídico</span><br>
                         juridico@adoteumgatinho.org.br
                      </p>
                    </a>
                  </li>
                  <li class="collection-item" style="line-height: 32px">    
                        <a href="mailto:informacoes@adoteumgatinho.org.br">                
                          <!-- <img src="http://lorempixel.com/50/50/cats/3" alt="" class="circle"> -->
                          <span class="title bold upper aug_orange truncate">Tatiana del Valle</span>
                          <p class="aug_black truncate"><span class="bold">Informações gerais sobre o AUG</span><br>
                             informacoes@adoteumgatinho.org.br
                          </p>
                         </a>
                   </li>
                   <li class="collection-item" style="line-height: 32px">
                        <a href="mailto:lojinha@adoteumgatinho.org.br">
                              <!-- <img src="http://lorempixel.com/50/50/cats/5" alt="" class="circle"> -->
                              <span class="title bold upper aug_orange truncate">Yone Sassa</span>
                              <p class="aug_black truncate"><span class="bold">Lojinha</span><br>
                                 lojinha@adoteumgatinho.org.br
                              </p> 
                        </a>
                    </li>
                </ul>
            </div>

        <h1 class="col s12 text_15 bold upper aug_orange">Redes Sociais</h1>
            <!-- (div.col.s12.m4.l3>div.card-panel.z-depth-1.border_b_orange>div.row.valign-wrapper>div.col.s2>img.circle.responsive-img)*4 -->
            <div class="col s12 m6">
                <ul class="collection">
                    <li class="collection-item" style="line-height: 32px">
                        <a href="mailto:carol.zanni@adoteumgatinho.org.br ">
                              <!-- <img src="http://lorempixel.com/200/200/cats/3" alt="" class="circle"> -->
                              <span class="title bold upper aug_orange truncate">Carol Zanni</span>
                              <p class="aug_black truncate"><span class="bold">Supervisão Facebook</span><br>
                                 carol.zanni@adoteumgatinho.org.br 
                              </p> 
                        </a>
                    </li>
                </ul>

                <ul class="collection">
                    <li class="collection-item bold">Fabiana Fernandes</li>
                    <li class="collection-item bold">Larissa Lourencini</li>
                    <li class="collection-item bold">Mariana Sacramento</li>
                    <li class="collection-item bold">Paula Guima</li>
                </ul>
            </div>

            <div class="col s12 m6">
                <ul class="collection">
                    <li class="collection-item" style="line-height: 32px">
                        <a href="mailto:denise@adoteumgatinho.org.br">
                              <!-- <img src="http://lorempixel.com/200/200/cats/3" alt="" class="circle"> -->
                              <span class="title bold upper aug_orange truncate">Denise Granja</span>
                              <p class="aug_black truncate"><span class="bold">Supervisão Twitter e Instagram</span><br>
                                 denise@adoteumgatinho.org.br
                              </p> 
                        </a>
                    </li>
                </ul>
                <ul class="collection">
                    <li class="collection-item bold">Ana Catarina</li>
                    <li class="collection-item bold">Ana Paula Ramos</li>
                    <li class="collection-item bold">Juliana Chang</li>
                    <li class="collection-item bold">Maria Thereza Russo Olivo</li>
                </ul>
            </div>

            <h1 class="col s12 text_15 bold upper aug_orange">Site/Fotos</h1>
            <!-- (div.col.s12.m4.l3>div.card-panel.z-depth-1.border_b_orange>div.row.valign-wrapper>div.col.s2>img.circle.responsive-img)*4 -->
            <div class="col s12">
                <ul class="collection">
                    <li class="collection-item" style="line-height: 32px">
                        <a href="mailto:clotilde@adoteumgatinho.org.br">
                              <!-- <img src="http://lorempixel.com/200/200/cats/3" alt="" class="circle"> -->
                              <span class="title bold upper aug_orange truncate">Clotilde Jalles</span>
                              <p class="aug_black truncate"><span class="bold">Site/Fotos</span><br>
                                 clotilde@adoteumgatinho.org.br
                              </p> 
                        </a>
                    </li>
                </ul>

                <ul class="collection">
                    <li class="collection-item bold">Bruna Lora</li>
                    <li class="collection-item bold">Carina Guiname</li>
                    <li class="collection-item bold">Caroline Barrionuevo</li>
                    <li class="collection-item bold">Luciana Musolino</li>
                    <li class="collection-item bold">Newton Zoubaref</li>
                </ul>
            </div>

            <h1 class="col s12 text_15 bold upper aug_orange">Apadrinhamento</h1>
            <!-- (div.col.s12.m4.l3>div.card-panel.z-depth-1.border_b_orange>div.row.valign-wrapper>div.col.s2>img.circle.responsive-img)*4 -->
            <div class="col s12">
                <ul class="collection">
                    <li class="collection-item" style="line-height: 32px">
                        <a href="mailto:apadrinhamento@adoteumgatinho.org.br">
                              <!-- <img src="http://lorempixel.com/200/200/cats/1" alt="" class="circle"> -->
                              <span class="title bold upper aug_orange truncate">Bell Adeira</span>
                              <p class="aug_black truncate"><span class="bold">Apadrinhamento</span><br>
                                 apadrinhamento@adoteumgatinho.org.br
                              </p> 
                        </a>
                    </li>
                </ul>
                <ul class="collection">
                    <li class="collection-item col s12 bold">Carol Toledo</li>
                    <li class="collection-item col s12 bold">Neise Gianesella</li>
                    <li class="collection-item col s12 bold">Renata Pereira</li>
                </ul>
                   

            </div>

     <h1 class="col s12 text_15 bold upper aug_orange">Atendimento às visitas ao abrigo</h1>
        <ul class="collection">
            <li class="collection-item col s12 m6 bold">Ana Catarina</li>
            <li class="collection-item col s12 m6 bold">Bianca Morelli</li>
            <li class="collection-item col s12 m6 bold">Christina Santos</li>
            <li class="collection-item col s12 m6 bold">Dani Xavier</li>
            <li class="collection-item col s12 m6 bold">Isabella Nacco</li>
            <li class="collection-item col s12 m6 bold">Maria Carolina</li>
            <li class="collection-item col s12 m6 bold">May Edelstein</li>
            <li class="collection-item col s12 m6 bold">Mayara Manzi</li>
            <li class="collection-item col s12 m6 bold">Priscilla Costa</li>
            <li class="collection-item col s12 m6 bold">Sati Petrelli</li>
            <li class="collection-item col s12 m6 bold">Sati Thais</li>
            <li class="collection-item col s12 m6 bold">Vanessa Moser Rocco</li>
        </ul>

     <h1 class="col s12 text_15 bold upper aug_orange">Lares temporários e entrega dos gatos reservados</h1>
        
        <ul class="collection">
            <li class="collection-item col s12 m6 bold">Ana Paula Ramos</li>
            <li class="collection-item col s12 m6 bold">André Cavallari</li>
            <li class="collection-item col s12 m6 bold">Andréa Moraes</li>
            <li class="collection-item col s12 m6 bold">Andressa Zamai</li>
            <li class="collection-item col s12 m6 bold">Bell Adeira</li>
            <li class="collection-item col s12 m6 bold">Bianca Morelli</li>
            <li class="collection-item col s12 m6 bold">Chris Santos</li>
            <li class="collection-item col s12 m6 bold">Cris de Almeida</li>
            <li class="collection-item col s12 m6 bold">Dani Carmignani</li>
            <li class="collection-item col s12 m6 bold">Dani Xavier</li>
            <li class="collection-item col s12 m6 bold">Gisele Genova</li>
            <li class="collection-item col s12 m6 bold">Isabella Nacco</li>
            <li class="collection-item col s12 m6 bold">Jaque Dulley</li>
            <li class="collection-item col s12 m6 bold">Juliana Bussab</li>
            <li class="collection-item col s12 m6 bold">Laraue Motta</li>
            <li class="collection-item col s12 m6 bold">Lia Nasi </li>
            <li class="collection-item col s12 m6 bold">Lucy Cardia</li>
            <li class="collection-item col s12 m6 bold">Marcela Teixeira</li>
            <li class="collection-item col s12 m6 bold">Maria Carolina</li>
            <li class="collection-item col s12 m6 bold">Marília Silveira</li>
            <li class="collection-item col s12 m6 bold">Marina Coelho da Cunha</li>
            <li class="collection-item col s12 m6 bold">May Edelstein</li>
            <li class="collection-item col s12 m6 bold">Mayara Manzi</li>
            <li class="collection-item col s12 m6 bold">Priscila Garcia</li>
            <li class="collection-item col s12 m6 bold">Priscilla Costa</li>
            <li class="collection-item col s12 m6 bold">Raquel Rignani</li>
            <li class="collection-item col s12 m6 bold">Renata Tasso</li>
            <li class="collection-item col s12 m6 bold">Rosa Dionizio</li>
            <li class="collection-item col s12 m6 bold">Sati Petrelli</li>
            <li class="collection-item col s12 m6 bold">Silvia Garwood</li>
            <li class="collection-item col s12 m6 bold">Solange Garcia</li>
            <li class="collection-item col s12 m6 bold">Susan Yamamoto</li>
            <li class="collection-item col s12 m6 bold">Vanessa Moser</li>
            <li class="collection-item col s12 m6 bold">Yone Sassa</li>
        </ul>

        <h1 class="col s12 text_15 bold upper aug_orange">Lares temporários para Grávidas e Lactantes</h1>

        <ul class="collection">
            <li class="collection-item" style="line-height: 32px">
                <a href="mailto:jaqueline@adoteumgatinho.org.br">
                      <!-- <img src="http://lorempixel.com/200/200/cats/3" alt="" class="circle"> -->
                      <span class="title bold upper aug_orange truncate">Supervisão</span>
                      <p class="aug_black truncate"><span class="bold">Jaqueline Suryan</span><br>
                         Jaqueline@adoteumgatinho.org.br
                      </p> 
                </a>
            </li>
        </ul>

        <ul class="collection">
            <li class="collection-item col s12 m6 l4 bold">André Cavallari</li>
            <li class="collection-item col s12 m6 l4 bold">Carina Guiname</li>
            <li class="collection-item col s12 m6 l4 bold">Cintia Plati</li>
            <li class="collection-item col s12 m6 l4 bold">Hellen Domingos</li>
            <li class="collection-item col s12 m6 l4 bold">Isabella Nacco</li>
            <li class="collection-item col s12 m6 l4 bold">Leticia/Diogenes</li>
            <li class="collection-item col s12 m6 l4 bold">Nancy Marton</li>
            <li class="collection-item col s12 m6 l4 bold">Patrícia Freire</li>
            <li class="collection-item col s12 m6 l4 bold">Patrícia Oliveira</li>
            <li class="collection-item col s12 m6 l4 bold">Renata Pereira</li>
            <li class="collection-item col s12 l8 bold">Suelen Gajus</li>
        </ul>
    
        <h1 class="col s12 text_15 bold upper aug_orange">Transporte para exames, consultas e internações</h1>

        <ul class="collection">
            <li class="collection-item col s12 m6 bold">Alexandra Chiacchio</li>
            <li class="collection-item col s12 m6 bold">Andrea Caparroz</li>
            <li class="collection-item col s12 m6 bold">Angelica Amano</li>
            <li class="collection-item col s12 m6 bold">Carol Barreto</li>
            <li class="collection-item col s12 m6 bold">Carolina Zoccarato Pereira</li>
            <li class="collection-item col s12 m6 bold">Daniela Plummer</li>
            <li class="collection-item col s12 m6 bold">Hesmington</li>
            <li class="collection-item col s12 m6 bold">Kika Capellano</li>
            <li class="collection-item col s12 m6 bold">Lourdes</li>
            <li class="collection-item col s12 m6 bold">Larissa Lourencini</li>
            <li class="collection-item col s12 m6 bold">Rosa Dionísio</li>
            <li class="collection-item col s12 m6 bold">Stella Maris</li>
            <li class="collection-item col s12 bold">Virginia Marques</li>
        </ul>

    

        <h1 class="col s12 text_15 bold upper aug_orange">Criação e Arte</h1>
            
            <ul class="collection">
                <li class="collection-item col s12 l6" style="line-height: 32px">    
                    <a href="carol.zanni@adoteumgatinho.org.br">                
                      <!-- <img src="http://lorempixel.com/200/200/cats/3" alt="" class="circle"> -->
                      <span class="title bold upper aug_orange truncate">Carol Zanni</span>
                      <p class="aug_black truncate"><span class="bold">Criação e Arte</span><br>
                         carol.zanni@adoteumgatinho.org.br
                      </p>
                     </a>
               </li>
                <li class="collection-item col s12 l6" style="line-height: 32px">
                    <a href="mailto:rosa@adoteumgatinho.org.br">
                          <!-- <img src="http://lorempixel.com/200/200/cats/1" alt="" class="circle"> -->
                          <span class="title bold upper aug_orange truncate">Rosa Yukari</span>
                          <p class="aug_black truncate"><span class="bold">Criação e Arte</span><br>
                             rosa@adoteumgatinho.org.br
                          </p> 
                    </a>
                </li>
               

            </ul>
            
        <h1 class="col s12 text_15 bold upper aug_orange">Nota Fiscal Paulista</h1>
           <ul class="collection">
                <li class="collection-item col s12" style="line-height: 32px">         
                      <!-- <img src="http://lorempixel.com/200/200/cats/3" alt="" class="circle"> -->
                      <span class="title bold upper aug_orange truncate">Carolina Medeiros</span>
                      <p class="aug_black truncate"><span class="bold">Coordenação</span><br>
                      </p>
               </li>
            </ul>

        <ul class="collection">
            <li class="collection-item bold col s12 m6">Adriana Maciel</li>
            <li class="collection-item bold col s12 m6">Eliza de Paula</li>
            <li class="collection-item bold col s12 m6">Erika Leonetti</li>
            <li class="collection-item bold col s12 m6">Karla M. Ruivo</li>
            <li class="collection-item bold col s12 m6">Patricia Freire</li>
            <li class="collection-item bold col s12 m6"> Raquel Rodrigues</li>
            <li class="collection-item bold col s12"> Rubia Elias</li>
        </ul>


        <h1 class="col s12 text_15 bold upper aug_orange">Compras</h1>

        <ul class="collection">
            <li class="collection-item bold">Ana Paula Cortez</li>
            <li class="collection-item bold">Fernanda Calado</li>
            <li class="collection-item bold">Kika Cappellano</li>
        </ul>
    

        <h1 class="col s12 text_15 bold upper aug_orange">Financeiro</h1>

        <ul class="collection">
                <li class="collection-item" style="line-height: 32px">    
                  <a href="mailto:custos@adoteumgatinho.org.br">     
                      <!-- <img src="http://lorempixel.com/200/200/cats/4" alt="" class="circle"> -->
                      <span class="title bold upper aug_orange truncate">Ana Paula Cortez </span>
                      <p class="aug_black truncate"><span class="bold">Financeiro</span><br>
                      custos@adoteumgatinho.org.br
                      </p>
                  </a>
               </li>
                <li class="collection-item" style="line-height: 32px">
                    <a href="mailto:susan@adoteumgatinho.org.br">
                          <!-- <img src="http://lorempixel.com/200/200/cats/3" alt="" class="circle"> -->
                          <span class="title bold upper aug_orange truncate">Susan Yamamoto</span>
                          <p class="aug_black truncate"><span class="bold">Financeiro</span><br>
                             susan@adoteumgatinho.org.br
                          </p> 
                    </a>
                </li>
               

            </ul>

           
        <h1 class="col s12 text_15 bold upper aug_orange">Equipe Veterinária</h1>

        <ul class="collection">
            <li class="collection-item" style="line-height: 32px">
                <a href="mailto:jaqueline@adoteumgatinho.org.br">
                      <!-- <img src="http://lorempixel.com/200/200/cats/3" alt="" class="circle"> -->
                      <span class="title bold upper aug_orange truncate">Responsável Técnica</span>
                      <p class="aug_black truncate"><span class="bold">Dra. Angélica Lang Klaussner</span><br>
                         CRMV - SP 9579
                      </p> 
                </a>
            </li>
        </ul>

        <ul class="collection">
            <li class="collection-item bold">Dra Gabriela Camargo</li>
            <li class="collection-item bold">Dra Maria Helena</li>
            <li class="collection-item bold">Dra Nilia Vieira</li>
            <li class="collection-item bold">Mayara Alves Mello (auxiliar veterinária)</li>
            <!-- <li class="collection-item bold">Sati</strong> (aplicação de Reiki)</li> -->
        </ul>
        
        <h1 class="col s12 text_15 bold upper aug_orange">Conheça o fluxo de trabalho da equipe Adote um Gatinho</h1>

        <img src="<?php echo HOST;?>img/info2.jpg" alt="" class="responsive-img m-b-20">
        </div>

    </div>
</div>