<?php 
$breadColor = 'purple';
$breadPaths = array();
$lastPath = 'Adotar um ou dois gatinhos';
include('top.phtml'); 

?>

<div class="aug_grey_bg m-b-0">
	    <div class="image-background-text" style="background-image: url('<?php echo HOST;?>midia/um-ou-dois-gatinhos.jpg')" style="position: relative;">
            <div class="gradiente"></div>

            <article class="col s12 l4 offset-l1 news-title">
                <div class="heading upper aug_purple_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">Um ou dois?</div>
                <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">O QUE É MELHOR? ADOTAR UM OU DOIS GATINHOS?</h2>
                <!-- <h3 class="italic white-text text_10 col s12 m6" style="margin-top: -20px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos aperiam harum ducimus esse, laborum provident necessitatibus pariatur eius obcaecati sapiente nihil est, soluta eveniet maxime commodi deserunt atque dolores ipsam.</h3> -->
            </article>
        </div>
	    	<article class="row container-large m-b-0">
	    	
	    		<div class="col s12" style="margin-top: 50px; margin-bottom: 50px;">
					<p class="text_10">A maioria das pessoas têm medo de adotar dois gatinhos de uma vez. Medo de não dar conta do recado, de ter muita despesa, de ter muita bagunça em casa, medo de tudo!</p>
					<p class="text_10 m-t-10">Fica na cabeça: mas e se não der certo?</p>
					<p class="text_10 m-t-10">Então elas adotam um gatinho só. Curioso que, passado algum tempo, elas voltam a nos procurar para adotar uma companhia para o primeiro gatinho.</p>
					<p class="text_10 m-t-10">É melhor adotar dois gatinhos de uma vez? Sim! E não é papo de "vendedor", nós explicamos o porquê:</p>

					<ul class="row text_10 m-t-10 aug_purple col s12 bold text_13">
						<li class="col s10 offset-s1 lista-texto m-t-20">os gatinhos vão brincar juntos, dormir juntos, dividir os potinhos e a caixinha de areia. Crescerão mais sociáveis e menos mimados, consequentemente, menos dependentes;</li>
						<li class="col s10 offset-s1 lista-texto m-t-20">não estamos contando as vacinas e tratamento veterinário que eles possam vir a precisar, mas o gasto "básico" que você vai ter será só um pouquinho maior, com ração e areia. Potinhos e caixinha podem ser divididos;</li>
						<li class="col s10 offset-s1 lista-texto m-t-20">você não correrá o risco de seu gatinho ficar deprimido ou sentir muito a sua falta quando você for trabalhar ou passar o fim de semana fora. Ele ficará bem e você poderá ficar despreocupado;</li>
						<li class="col s10 offset-s1 lista-texto m-t-20">você não terá problema com adaptação no futuro, já que os gatinhos chegarão juntos;</li>
						<li class="col s10 offset-s1 lista-texto m-t-20">gatos que se sentem muito sozinhos podem ficar doentes (depressão) ou tentar adquirir manias para chamar a sua atenção, como fazer xixi em lugar errado, afiar as unhas em seus objetos etc.</li>
					</ul>

				<!-- <div class="col s12 m5 text_15 pull-m1 m-t-20 m-b-20 text-right aug_purple" style="font-weight: lighter;"><em>"Com as devidas precauções, um gatinho FIV pode viver 10 anos ou mais. A maneira como o gato infectado irá apresentar a doença dependerá da fase da vida em que ele foi contaminado. Filhotes e adolescentes tentem a desenvolver a doença de uma forma mais agressiva."</em></div>
 -->

					<p class="text_10 m-t-10">Lembramos que não são todos os gatinhos que precisam de companhia. Há gatos que vivem bem sozinhos, que se adaptam muito bem. Comparados aos cachorros eles são sim mil vezes mais independentes. Mas não há uma regra. Cada gatinho tem um temperamento diferente, um comportamento diferente, não dá para generalizar. Só sabemos de uma coisa: ter dois gatinhos é uma fórmula sem erro.</p>
				</div>
			</article>
		</div>