<?php 
$breadColor = 'blue';
$breadPaths = array('Gatinhos para adoção'=>'#', 'Formulário'=>'#');
$lastPath = 'Sucesso';
include('top.phtml'); 

?>
<section class="row m-b-0">
    <article class="col s10 offset-s1">
        <h2 class="h1 aug_blue">Obrigado!</h2>
        <p>Seu pedido de adoção foi cadastrado com sucesso.</p>
        <p>A equipe Adote Um Gatinho entrará em contato em breve</p>
        
        <a class="perfil left bt bt_gray m-t-20 aug_blue" href="javascript:history.back()">Voltar</a>
	</article>
</section>
