<?php
$breadColor = 'purple';
$breadPaths = array();
$lastPath = 'Esporotricose';
include('top.phtml');

?>
    <div class="aug_grey_bg m-b-0">
        <div class="image-background-text" style="background-image: url('http://adoteumgatinho.org.br/midia/esporotricose.jpg')" style="position: relative;">
            <div class="gradiente"></div>

            <article class="col s12 l4 offset-l1 news-title">
                <!-- <div class="heading upper aug_purple_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">Mamadeiras</div> -->
                <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">Esporotricose</h2>
                <h3 class="italic white-text text_10 col s12 m6" style="margin-top: -20px;">Existe uma doença chamada esporotricose, causada por um fungo, e infelizmente ela afeta pessoas e outros animais, inclusive o gato. Acontece que a disseminação entre os gatos atualmente é grande. Existem hoje milhares de gatos contaminados e o nosso amigo felino está levando a fama de vilão. Mas ele é apenas mais uma vítima...</h3>
            </article>
        </div>
        <article class="row container-large m-b-0 maxw-960">

            <div class="col s12 m-t-20">
                <h5 class="m-b-10 aug_purple">A esporotricose</h5>
                <p class="m-b-10">A esporotricose é uma doença causada pelo fungo Sporothrix schenckii, encontrado na terra, madeira, palha etc. Antigamente ela era conhecida como “doença do jardineiro” ou “doença da roseira”. A esporotricose existe no mundo todo e principalmente em regiões quentes e úmidas.</p>
                <p class="m-b-10">No gato, aparecem lesões na pele, avermelhadas e elevadas, geralmente com pus.  Sem tratamento, as lesões aumentam e se espalham pelo corpo.</p>
                <p class="m-b-10">Em casos mais graves, a esporotricose pode afetar os órgãos internos, como o pulmão e o sistema nervoso, e levar à morte. Nesse estágio, os gatos podem ter febre, apatia, falta de apetite, perda de peso e respirarem com dificuldade.</p>
                <p class="m-b-10">Nos humanos, aparecem pequenos caroços, que podem virar feridas. São vermelhos e normalmente enfileirados.</p>

                <h5 class="m-b-10 aug_purple">Como se adquire esporotricose?</h5>

                <p class="m-b-10">O fungo precisa de uma brecha na pele para entrar. Os gatos se contaminam na terra ou em brigas com outros gatos. Basta levar um arranhão ou mordida de um animal infectado para se contaminar.</p>
                <p class="m-b-10">As pessoas pegam esporotricose da mesma forma, diretamente da terra ou em algum pequeno acidente, esbarrando em uma tábua de madeira contaminada, por exemplo, e também do arranhão ou mordida de um gato ou outro animal contaminado.</p>
            </div>
                <div class="col s10 m10 offset-s1">
                    <p class="aug_purple bold text_13 m-t-20 m-b-20">
                        A esporotricose é uma doença causada pelo fungo Sporothrix schenckii, encontrado na terra, madeira, palha etc. Antigamente ela era conhecida como “doença do jardineiro” ou “doença da roseira”. A esporotricose existe no mundo todo e principalmente em regiões quentes e úmidas.
                    </p>
                </div>
            <div class="col s12 m-b-20">
                <p class="m-b-10">É possível adquirir pelo ar, inalando o fungo, mas é algo bem raro.</p>
                <p class="m-b-10">Não há registro de contágio de pessoa para pessoa.</p>
                <h5 class="aug_purple m-b-10">Acho que meu gato está com esporotricose...</h5>
                <p class="m-b-10">Calma, não é motivo para pânico. Isole o gatinho em um cômodo e use luvas para manipulá-lo. Lembre-se sempre de lavar bem as mãos mesmo assim. Limpe sua casa com água sanitária ou cloro. E leve o gatinho para uma avaliação veterinária. Provavelmente o veterinário irá realizar uma biópsia para entender o que são as lesões ou encaminhá-lo para um dermatologista.</p>
                <h5 class="m-b-10 aug_purple">Confirmei: meu gato está com esporotricose!</h5>
                <p class="m-b-10">Mantenha os cuidados, limpando o ambiente com água sanitária e cloro, usando luvas e lavando bem as mãos após o contato com o gatinho. O veterinário irá prescrever o tratamento, com antifúngico itraconazol e, dependendo da gravidade, associar outro fármaco, como o iodeto de potássio. Mas atenção: não medique sem orientação veterinária porque a dosagem e o tempo do tratamento podem variar e é preciso seguir o tratamento à risca para que seja eficaz. O tratamento é longo, leva pelo menos 6 meses, mas pode chegar a 1 ou 2 anos. Não abandone o seu gatinho, ele é seu filho, seu amigo, e sem assistência vai passar a doença para gatos sadios e poderá morrer. </p>
                <p class="m-b-10">Se hoje temos tantos casos de gatinhos doentes na rua não é só porque o fungo existe no ambiente, mas porque as pessoas abandonam os seus gatos e eles estão passando a doença para frente. Seja responsável, tenha coração. O gato não é o vilão dessa história!</p>
                <p class="m-b-10">Importante: O texto que escrevemos é feito com base na nossa experiência com nossos gatinhos. Consulte um veterinário para mais informações.</p>
            </div>
        </article>
    </div>
<!-- </div> -->
