<!-- VIEW NOVA  -->
<?php 
$breadColor = 'purple'; // aqui ele escolhe a cor de fundo da busca (orange, purple, blue)
$breadPaths = array();  // Pra definir os caminhos intermediários do breadcrumb, é só colocar nesse formato 'chave'=> 'valor' separado por vírgulas
$lastPath = 'Quero adotar'; // a página atual, último nível do breadcrumb
include('top.phtml'); // view em si

?> 

<div class="aug_grey_bg">
 
<nav class="col s12">
    <ul class="aug_tabs white">
        <li class="col s3"><a href="<?php echo HOST;?>quero-adotar" class="active">Quero adotar</a></li>
        <li class="col s3"><a href="<?php echo HOST;?>materias">Mais matérias</a></li>
  </ul>
</nav>
 
  <div class="row container-large m-b-0">
   
<!--   TAB 2-->
    <div class="col s12" id="mais-acessados">
     <h1 class="col s12 aug_purple bold upper h1">Quero Adotar</h1>
       
       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>gatinhos-para-adocao">
                   <div align="center">
                     <div class="activator icon-purple ic-cat-tooth info-quero-adotar"></div>
                   </div>
<!--                     <img class="activator" src="<?php echo HOST;?>img/gatinhos-para-adocao.jpg" /> -->
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Gatinhos para adoção</span>
                <p class="m-t-10">Veja os gatinhos que estão a espera de um lar e de muito carinho</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>gatinhos-para-adocao" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>adocoes-especiais">
                   <div align="center">
                     <div class="activator icon-purple ic-looking-cat info-quero-adotar"></div>
                   </div>
<!--                     <img class="activator" src="<?php echo HOST;?>img/gatinhos-para-adocao.jpg" /> -->
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Adoções Especiais</span>
                <p class="m-t-10">Eles também merecem um lar. Conheça os nossos gatinhos especiais e se apaixone.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>gatinhos-para-adocao" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>como-adotar-um-gatinho">
                    <div align="center">
                     <div class="activator icone-adocao info-quero-adotar"></div>
                    </div>
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Como faço para adotar um gatinho?</span>
                <p class="m-t-10">Veja aqui o fluxograma com o passo a passo.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>como-adotar-um-gatinho" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>  

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>
politica-de-adocao-aug">
                    <div align="center">
                     <div class="activator icon-purple ic-ok-doc info-quero-adotar"></div>
                    </div>
                    <!-- <img class="activator" src="<?php echo HOST;?>img/politica-de-adocao.jpg" alt="" /> -->
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Política de adoção</span>
                <p class="m-t-10">Conheça os critérios de adoção do Adote um Gatinho.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>
politica-de-adocao-aug" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

      <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image p-t-large-card">
                   <a href="<?php echo HOST;?>depoimentos">
                    <div align="center">
                     <div class="activator icon-purple ic-letter info-quero-adotar"></div>
                    </div>
                    <!-- <img class="activator" src="<?php echo HOST;?>img/depoimentos.jpg" alt="" /> -->
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Depoimentos</span>
                <p class="m-t-10">Finais felizes! Nossos gatinhos mandam notícias dos seus novos lares!</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>depoimentos" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>      
    
      <h1 class="col s12 aug_purple bold upper h1" id="Informacoes-importantes">Informações Importantes</h1>
      <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>preparado-para-adotar">
                    <img class="activator" src="<?php echo HOST;?>img/preparado-para-adotar-mini.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Preparado para adotar?</span>
                <p class="m-t-10">Veja se você realmente está preparado e tem condições de adotar um gatinho!</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>
preparado-para-adotar" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>
       
       
       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                <a href="<?php echo HOST;?>um-ou-dois-gatinhos">
                    <img class="activator" src="<?php echo HOST;?>img/um-ou-dois-gatinhos-mini.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Um ou dois gatinhos?</span>
                <p class="m-t-10">O que é melhor, adotar um ou dois gatinhos? Descubra!</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>um-ou-dois-gatinhos" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>
       
       
       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
               <a href="<?php echo HOST;?>a-importancia-da-castracao">
                    <img class="activator" src="<?php echo HOST;?>img/importancia-castracao-mini.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">A importância da castração</span>
                <p class="m-t-10">Castrar seu gatinho é essencial por vários motivos! Confira também locais para onde levar seu bichinho para ser operado a um custo mais acessível.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>a-importancia-da-castracao" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>
       

      <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
               <a href="<?php echo HOST;?>telas-nas-janelas">
                    <img class="activator" src="<?php echo HOST;?>img/telas-nas-janelas-mini.jpg" alt="" />
                    
              </a>
              
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Telas nas janelas</span>
                <p class="m-t-10">Telas são item obrigatório para quem quer adotar um gatinho. Não é frescura, não! Veja o porquê.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>telas-nas-janelas" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

      <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>toxoplasmose">
                    <img class="activator" src="<?php echo HOST;?>img/toxoplasmose-mini.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Toxoplasmose</span>
                <p class="m-t-10">Saiba o que é mito e o que é verdade em relação ao assunto.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>toxoplasmose" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>fiv">
                    <img class="activator" src="<?php echo HOST;?>img/FIV-mini.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">FIV: AIDS Felina</span>
                <p class="m-t-10">Ter um gatinho com FIV (AIDS felina) em casa é mais tranquilo do que se pensa. Com alguns cuidados simples, ele poderá ter uma vida longa e feliz.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>fiv" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>felv">
                    <img class="activator" src="<?php echo HOST;?>img/felv-mini.jpg" alt="" />
                    
                  </a>
                  
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">FeLV: Leucemia Felina</span>
                <p class="m-t-10">FeLV é leucemia felina, ou seja, ela é exclusiva de gatos. Ela é causada por um vírus e a contaminação pode acontecer quando gatos se mordem, se lambem ou compartilham caixas de areia, potes de água e comida.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>felv" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>

       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>pif">
                    <img class="activator" src="<?php echo HOST;?>img/pif-mini.jpg" alt="" />
                  </a>
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">PIF: Peritonite Infecciosa Felina</span>
                <p class="m-t-10">A PIF é uma das doenças que mais assustam os donos de gatos. Leia mais sobre ela aqui.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>pif" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>
       
       <section class="col s12 m6 l4">
           <div class="large card plus card-wrapper">
              <div class="card-image">
                   <a href="<?php echo HOST;?>pif">
                    <img class="activator" src="<?php echo HOST;?>img/materias-mini.jpg" alt="" />
                  </a>
              </div>
              <div class="card-content">
                <span class="card-title bold aug_purple m-b-10" style="line-height: 24px; text-shadow: none; background-color: transparent;">Mais matérias</span>
                <p class="m-t-10">Clique e acesse outros conteúdos importantes sobre como cuidar do seu gatinho.</p>
              </div>
              <div class="card-action border_b_purple">
                <a href="<?php echo HOST;?>materias/" class="col s12 bold text_13 text-right aug_purple_btn">Clique Aqui</a>
              </div>
            </div>
       </section>
    </div>      
  </div> 
</div>   
