<?php
$breadColor = 'purple';
$breadPaths = array();
$lastPath = 'Mamadeiras';
include('top.phtml');
?>
    <div class="aug_grey_bg m-b-0">
        <div class="image-background-text" style="background-image: url('http://adoteumgatinho.org.br/midia/mamadeiras.jpg')" style="position: relative;">
            <div class="gradiente"></div>

            <article class="col s12 l4 offset-l1 news-title">
                <div class="heading upper aug_purple_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">Mamadeiras</div>
                <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">CUIDADOS COM MAMADEIRAS, BEBÊS GATINHOS SEM MÃE</h2>
                <!-- <h3 class="italic white-text text_10 col s12 m6" style="margin-top: -20px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos aperiam harum ducimus esse, laborum provident necessitatibus pariatur eius obcaecati sapiente nihil est, soluta eveniet maxime commodi deserunt atque dolores ipsam.</h3> -->
            </article>
        </div>
        <article class="row container-large m-b-0 maxw-960">

            <div class="col s12 m-t-20">
                <p class="m-b-10">O primeiro passo é deixá-los aquecidos. Recém-nascidos não conseguem manter a temperatura corporal sozinhos.</p>
                <p class="m-b-10">Coloque uma bolsa de água quente (quente o suficiente para não queimá-los!) e a envolva num paninho para evitar o contato direto na pele do bebê. Vale usar também uma garrafa pet pequena ou uma luva para procedimentos cirúrgicos. Esta última pode ser aquecida no micro-ondas por 12 segundos aproximadamente. Mantê-los aquecidos é essencial para a sobrevivência deles.</p>
                <p class="m-b-10">Para acomodá-los utilize uma caixa para transportes de pets ou uma caixa de papelão com paredes altas, pois conforme vão crescendo, costumam se arrastar e escalar, podendo sofrer uma queda.</p>
                <p class="m-b-10">Compre mamadeira especial à venda em pet shops. Indicamos usar uma que tenha bico de borracha e a com bico de silicone é recomendada para bebês extremamente pequenos que tenham dificuldade em aceitar a mamadeira. Mas atenção: quando o bebê começar a morder o bico da mamadeira, esta de silicone torna-se perigosa, porque pedacinhos podem se desprender e causar um engasgo que pode ser fatal. A mais recomenda é a Pet Nurse, já testamos algumas e sabemos que essa é a que funciona melhor.</p>
                <p class="m-b-10">Para a mamadeira, compramos leite em pó para gatinhos, também à venda em pet shops.</p>
                <p class="m-b-10">Ofereça a mamadeira a cada 2 horas e sempre com o gatinho em pé ou de barriga para baixo. Nunca de costas, senão ele pode aspirar o leite que vai para o pulmão e ele morre afogado. Nunca dê mamadeira se o bebê estiver com o corpinho frio, primeiro o aqueça e então o amamente. Recém-nascidos quando estão com frio, rejeitam a mamadeira, por isso a importância de mantê-los quentinhos.</p>
            </div>
                <div class="col s10 m10 offset-s1">
                    <p class="aug_purple bold text_13 m-t-20 m-b-20">
                        "Ofereça a mamadeira a cada 2 horas e sempre com o gatinho em pé ou de barriga para baixo. Nunca de costas, senão ele pode aspirar o leite que vai para o pulmão e ele morre afogado. Nunca dê mamadeira se o bebê estiver com o corpinho frio, primeiro o aqueça e então o amamente. Recém-nascidos quando estão com frio, rejeitam a mamadeira, por isso a importância de mantê-los quentinhos."
                    </p>
                </div>
            <div class="col s12 m-b-20">
                <p class="m-b-10">Sempre que você der mamadeira, pegue um algodão ou gaze úmida e faça movimentos circulares no pipi, no ânus e na barriguinha. Os gatinhos não sabem fazer as necessidades sozinhos (a mãe-gato os lambe) e precisam da sua ajuda. Normalmente eles vão urinar todas as vezes que forem estimulados, mas defecar nem sempre. Porém, fique atento: eles não podem ficar 3 dias seguidos sem defecar. Se isso acontecer, procure um veterinário urgente.</p>
                <p class="m-b-10">Recém-nascidos miam (choram) por 3 motivos básicos: frio, fome ou porque estão molhados pelo xixi. Se resolvendo esses motivos ele não parar de miar, leve-o ao veterinário.</p>
                <p class="m-b-10">Se os olhinhos estiverem com alguma remela, você pode limpar com um algodão embebido em soro fisiológico. No entanto, se a remela for exagerada, procure a ajuda de um veterinário.</p>
                <p class="m-b-10">Você pode também procurar por uma mamãe de leite, ou seja, uma gatinha que esteja amamentando filhotes da mesma idade. Muitas acabam adotando, mas é preciso ter cuidado para que os gatinhos não passem e nem peguem nenhuma doença da mãe de leite.</p>
                <p class="m-b-10">Com aproximadamente 30 dias os gatinhos já estarão procurando um lugar para fazerem suas necessidades e você pode apresentá-los a uma caixa de areia. É nesta época também que se pode começar a introduzir alimentos sólidos, tipo patê ou pastinha, e deixar ração seca à disposição. Em um determinado momento você verá que eles não aceitarão mais o leite e é importante que comecem a aprender a tomar água.</p>
                <p class="m-b-10">E desejamos de coração: boa sorte! Não é fácil cuidar de recém-nascidos, mas se eles vingam é uma alegria, um orgulho que não cabe dentro do peito!</p>
                <p class="m-b-10">Parabéns e muito obrigada por não ter fechado os olhos e ter socorrido esse(s) recém-nascido(s)!</p>
            </div>
        </article>
    </div>
<!-- </div> -->
