<?php
$breadColor = 'purple';
$breadPaths = array();
$lastPath = 'Gatos Ferais';
include('top.phtml');

?>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <div class="aug_grey_bg m-b-0">
        <div class="image-background-text" style="background-image: url('http://adoteumgatinho.org.br/midia/gatos-ferais.JPG'); background-position: center;">
            <div class="gradiente"></div>

            <article class="col s12 l4 offset-l1 news-title">
                <div class="heading upper aug_purple_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">Gatos Ferais</div>
                <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">Mitos sobre os gatos ferais e como você pode ajudar</h2>
                <!-- <h3 class="italic white-text text_10 col s12 m6" style="margin-top: -20px;">Mitos sobre os gatos ferais e como você pode ajudar</h3> -->
            </article>
        </div>
        <article class="container m-b-0 p-20">
            <div class="row">
                <div class="col s12 m6 l4">
                    <div class="card medium mitos-verdades-ferais">
                        <div class="card-content">
                            <span class="card-title activator white light aug_purple">Mito<i class="material-icons right">more_vert</i></span>

                            <p class="activator text_13 text-center p-20">Gatos ferais são gatos que já tiveram um dono e estão na rua. Logo, não tem problema colocá-los dentro de casa.</p>
                        </div>
                        <div class="card-reveal" style="padding: 0">
                            <span class="card-title white light aug_purple">Fato<i class="material-icons right m-0">close</i></span>
                            <p>Gatos de rua e gatos ferais são diferentes. Os de rua já tiveram dono e foram abandonados ou perdidos. Eles ficam tranquilos perto das pessoas e inclusive se aproximam delas para pedir comida. Gatos ferais, por outro lado, nasceram e viveram na rua sem contato com humanos. Eles podem ter sido gatos de rua, mas que ficaram tanto tempo sem contato com gente que acabaram se tornando ferais. De qualquer forma, os gatos ferais não chegam perto de pessoas voluntariamente e não se adaptarão a ficar dentro de casa.</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card medium mitos-verdades-ferais">
                        <div class="card-content">
                            <span class="card-title activator white light aug_purple">Mito<i class="material-icons right">more_vert</i></span>

                            <p class="activator text_13 text-center p-20">Gatos ferais são perigosos e precisam ser exterminados</p>
                        </div>
                        <div class="card-reveal" style="padding: 0">
                            <span class="card-title white light aug_purple">Fato<i class="material-icons right m-0">close</i></span>
                            <p>Gatos ferais são da mesma espécie do gatinho doméstico. Muitas vezes conhecidos como gatos comunitários, os ferais vivem em colônias e sobrevivem mesmo com condições precárias. Eles não oferecem perigo algum. Eles não se aproximam das pessoas e raramente são adotáveis.</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card medium mitos-verdades-ferais">
                        <div class="card-content">
                            <span class="card-title activator white light aug_purple">Mito<i class="material-icons right">more_vert</i></span>

                            <p class="activator text_13 text-center p-20">Gatos ferais atacam as pessoas.</p>
                        </div>
                        <div class="card-reveal" style="padding: 0">
                            <span class="card-title white light aug_purple">Fato<i class="material-icons right m-0">close</i></span>
                            <p>Os gatos ferais têm medo das pessoas e correrão para longe delas sempre que possível. Eles só atacam se forem acuados, ou seja, não faça isso.</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card medium mitos-verdades-ferais">
                        <div class="card-content">
                            <span class="card-title activator white light aug_purple">Mito<i class="material-icons right">more_vert</i></span>

                            <p class="activator text_13 text-center p-20">Gatos ferais passam doenças para as pessoas.</p>
                        </div>
                        <div class="card-reveal" style="padding: 0">
                            <span class="card-title white light aug_purple">Fato<i class="material-icons right m-0">close</i></span>
                            <p>Sem contato com as pessoas, eles não têm como passar doenças. Gatos ferais geralmente caçam roedores, o que faz deles uma barreira para as doenças. No entanto, as doenças em gatos ferais podem ser transmitidas para gatos domésticos que têm acesso à rua.</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card medium mitos-verdades-ferais">
                        <div class="card-content">
                            <span class="card-title activator white light aug_purple">Mito<i class="material-icons right">more_vert</i></span>

                            <p class="activator text_13 text-center p-20">Gatos ferais caçam pássaros.</p>
                        </div>
                        <div class="card-reveal" style="padding: 0">
                            <span class="card-title white light aug_purple">Fato<i class="material-icons right m-0">close</i></span>
                            <p>Alguns gatos, ferais ou domésticos, matam pássaros, mas são os humanos a verdadeira fonte de ameaça para eles, já que usam pesticidas e destroem o habitat das aves. Na verdade, os gatos ferais preferem comer roedores e lixo das casas.</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card medium mitos-verdades-ferais">
                        <div class="card-content">
                            <span class="card-title activator white light aug_purple">Mito<i class="material-icons right">more_vert</i></span>

                            <p class="activator text_13 text-center p-20">Gatos ferais são solitários que imploram por comida.</p>
                        </div>
                        <div class="card-reveal" style="padding: 0">
                            <span class="card-title white light aug_purple">Fato<i class="material-icons right m-0">close</i></span>
                            <p>Gatos ferais vivem em grupo na maioria dos casos, as chamadas colônias. Eles vivem onde os humanos não aparecem e onde encontram comida com facilidade. Eles são extremamente independentes e procuram por casas vazias, carros abandonados e chegam até a viver em tocas no chão para ficarem quentes no inverno e fresquinhos no calor.</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card medium mitos-verdades-ferais">
                        <div class="card-content">
                            <span class="card-title activator white light aug_purple">Mito<i class="material-icons right">more_vert</i></span>

                            <p class="activator text_13 text-center p-20">Gatos ferais deveriam ser levados a um abrigo para que possam ser colocados para adoção.</p>
                        </div>
                        <div class="card-reveal" style="padding: 0">
                            <span class="card-title white light aug_purple">Fato<i class="material-icons right m-0">close</i></span>
                            <p>Gatos ferais são selvagens e, por conta disso, têm pavor de gente. Eles demoram muito tempo até se acostumarem a ponto de poderem ser adotados, isso quando conseguem de fato mudar. Quando são levados para abrigos, passam a vida profundamente infelizes e escondidos.</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l4">
                    <div class="card medium mitos-verdades-ferais">
                        <div class="card-content">
                            <span class="card-title activator white light aug_purple">Mito<i class="material-icons right">more_vert</i></span>

                            <p class="activator text_13 text-center p-20">Gatos ferais vivem superbem e não precisam de ajuda.</p>
                        </div>
                        <div class="card-reveal" style="padding: 0">
                            <span class="card-title white light aug_purple">Fato<i class="material-icons right m-0">close</i></span>
                            <p>Gatos ferais não têm uma vida fácil. Eles lutam para sobreviver e têm que lidar com o clima, os riscos que a rua oferece, os ataques de outros animais e de pessoas. 50% dos gatos morrem de doenças ou por conta de parasitas antes de completarem um ano.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <p class="m-t-10 m-b-10">
                    Se você é um gateiro, ou se tem um coração batendo no peito, veja as dicas do que pode fazer para ajudar:
                </p>
                <ul>
                    <li class="aug_purple lista-texto bold text-13">Apoie campanhas de CED (captura, esterilização e devolução) como a que estamos fazendo em parceria com a Miados Urbanos.</li>
                    <li class="aug_purple lista-texto bold text-13">Seja responsável por uma colônia ou ajude alguém que faz esse trabalho.</li>
                    <li class="aug_purple lista-texto bold text-13">Na falta de ONG ou protetor na sua cidade, aprenda a fazer CED por conta própria. Peça orientação para quem já tem experiência com o trabalho.</li>
                    <li class="aug_purple lista-texto bold text-13">Se gatos ferais estão causando problemas no seu bairro, espalhe informação pela vizinhança antes que alguém resolva matá-los: estudos comprovaram que quando uma colônia é exterminada, é criado uma espécie de “efeito de vácuo” que faz com que novos gatos acabem se mudando para o mesmo local, atraídos pela fonte de alimentos que os gatos originais usavam.</li>
                    <li class="aug_purple lista-texto bold text-13">Compartilhe esse post com amigos e parentes!</li>
                </ul>
                <div class="m-t-10 m-b-10">
                    <hr>
                </div>
                <p class="m-t-10 m-b-10 text-right">
                    Adaptado de <a href="http://www.distractify.com/old-school/2014/10/15/national-feral-cat-day-1197796762" target="_blank" class="aug_purple bold">http://www.distractify.com/old-school/2014/10/15/national-feral-cat-day-1197796762</a>
                </p>
            </div>
        </article>
    </div>
</div>



<!-- # # # # # # # # # # # # # #
Footer
# # # # # # # # # # # # # # -->
<footer id="footer">
    <section class="row grey m-b-0">
        <!--       bloco 1-->
        <div class="col s12 m6 l3 offset-l1 hide-on-small-only">
            <strong>Adote um gatinho</strong>
            <p class="block-box">O Adote um Gatinho busca lares para gatos encontrados abandonados na Grande São Paulo e também trabalha para conscientizar as pessoas sobre a importância da castração e posse responsável.</p>
        </div>


        <!--bloco 2-->
        <menu class="col s12 m6 l4 hide-on-small-only">
            <strong>Menu</strong>
            <div class="col s6">
                <ul class="block-box">
                    <li><a href="http://adoteumgatinho.org.br/sobre">A ONG</a></li>
                    <li><a href="http://adoteumgatinho.org.br/quero-adotar">Quero adotar</a></li>
                    <li><a href="http://adoteumgatinho.org.br/quero-ajudar-a-aug">Quero ajudar</a></li>
                    <li><a href="http://adoteumgatinho.org.br/resgate">Resgate</a></li>
                    <li><a href="http://adoteumgatinho.org.br/gatos-adotados">Gatos adotados</a></li>
                    <li><a href="http://adoteumgatinho.org.br/prestacao-de-contas/contas?year=2016">Prestação de contas</a></li>
                </ul>
            </div>

            <div class="col s4">
                <ul class="block-box">
                    <li><a href="http://adoteumgatinho.org.br/aug-na-midia">Na mídia</a></li>
                    <li><a href="http://adoteumgatinho.org.br/boletins">Boletim AUG</a></li>
                    <li><a href="http://www.auglojinha.com.br/" target="_blank">Lojinha</a></li>
                    <li><a href="http://adoteumgatinho.org.br/faq">FAQ</a></li>
                    <li><a href="http://adoteumgatinho.org.br/parceiros-e-links">Parceiros</a></li>
                    <li><a href="http://adoteumgatinho.org.br/contato">Contato</a></li>
                </ul>
            </div>
        </menu>


        <!--Bloco 3-->
        <fieldset class="col s12 m12 l4">
            <strong class="hide-on-small-only">Siga o AUG</strong>
            <nav id="redes" class="col s12">
                <a href="http://www.facebook.com/adoteumgatinho" target="_blank" class="icon-white ic-facebook"></a>
                <a href="https://www.instagram.com/adoteumgatinho/?hl=pt-br" target="_blank" class="icon-white ic-instagram"></a>
                <a href="http://www.twitter.com/adoteumgatinho" class="icon-white ic-twitter" target="_blank"></a>
            </nav>

            <strong>Receba nossa newsletter</strong>
            <form class="block-box" method="post" id="newsletter-signup-form" action="http://adoteumgatinho.org.br/cadastre-se/confirmar">
                <div class="col s12 clear">
                    <input type="text" name="name" id="name" placeholder="Nome">
                    <input type="email"  name="email" id="email" placeholder="E-mail">
                    <button type="submit" class="icon-white ic-arrow-right"></button>
                </div>
            </form>
        </fieldset>
    </section>



    <div class="row upper grey darken-2 m-b-0 cancel-margin-40">
        <div class="col s8">
            2013 ~ 2018 - Adote um gatinho. Todos os direitos reservados.
        </div>
        <div class="col s4">
            <a href="http://www.elementodesign.com.br" target="_blank">Design by Elemento</a>
        </div>
    </div>
</footer>
<style>
table#Table_01, #Table_01 img{
    width: 100%!important;
    height:auto!important}
</style>


<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-3360136-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

<script src="http://adoteumgatinho.org.br/js/bin/materialize.min.js"></script>
<script src="http://adoteumgatinho.org.br/js/_main.min.js"></script>
</body>
</html>
