<?php 
$breadColor = 'purple';
$breadPaths = array();
$lastPath = 'Matérias';
include('top.phtml'); 

?>


<div class="grey lighten-4">
    <nav class="col s12">
    <ul class="aug_tabs">
        <li class="col s3"><a href="<?php echo HOST;?>quero-adotar">Quero adotar</a></li>
        <li class="col s3"><a href="<?php echo HOST;?>materias" class="active">Mais matérias</a></li>
  </ul>
</nav>
    
	<div class="row container m-b-0" id="todas">
		<header>
		    <h1 class="h1 bold aug_purple bold upper">Matérias</h1>
		</header>

		<?php foreach($this->data as $row):?>
			<section class="col s12 m6 l4">
				<div class="medium card card-wrapper">
					<div class="card-image">
					    <a class="more" href="<?php echo HOST;?>materia/<?php echo $row->id;?>/<?php echo str_replace(' ', '-', $row->title);?>">
	                        <?php if($row->picture == ''):?>
	                            <img src="<?php echo MEDIA_DIR;?>img_cat_not_found.png" alt="" />
	                        <?php else:?>
	                            <img src="<?php echo MEDIA_DIR.'uploads/news/'.$row->picture;?>" alt="" />
	                        <?php endif;?>
	                        <span class="card-title">
	                            <?php echo $row->title;?>
	                        </span>
	                    </a>
					</div>
					<div class="card-content">
						<?php
							if(strlen( $row->heading) > 120)
								 $row->heading = substr($row->heading, 0, 120) . '...';
							echo $row->heading
						?>
					</div>
					<div class="card-action border_b_purple">
						<a class="col s12 more bold text_13 text-right aug_purple_btn text-right" href="<?php echo HOST;?>materia/<?php echo $row->id;?>/<?php echo str_replace(' ', '-', $row->title);?>">Ler matéria</a>
					</div>
				</div>
			</section>
		<?php endforeach;?>
	</div>
</div>