<?php 
$breadColor = 'purple';
$breadPaths = array('Matérias'=>'materias');
$lastPath = $this->data->title;;
include('top.phtml'); 

?>

<div class="row container m-b-0 maxw-960">
	<h1 class="h1 bold upper aug_purple" style="margin-left: 0px;"><?php echo $this->data->title;?></h1>
	<p class="italic aug_purple subtext text_15"><?php echo $this->data->heading;?></p>
	
	<div class="text_10">
		<?php echo stripslashes($this->data->content);?>		
	</div>
	<div>
		<a style="float:right; margin-bottom: 15px;" class="perfil bt bt_purple right bold upper" href="javascript:history.go(-1);" style="display: inline-block; margin: 10px -10px; float: right;">Voltar</a>
	</div>
	<div class="clear"></div>
</div>