<?php 
$breadColor = 'blue';
$breadPaths = array('Cadastre-se'=>'cadastre-se');
$lastPath = 'Sucesso';
include('top.phtml'); 

?>
<section class="row m-b-0">
    <div class="col s12 m10 l10 offset-m1 offset-l1" id="dynamic-content">

    <h1 class="h1 aug_blue">Cadastro realizado com sucesso!</h1>
    <br>
    <p>A partir de agora, você receberá nossas newsletters!</p>
    <p>Muito obrigado!</p>

    </div>
    <div class="col s12 m10 l10 offset-m1 offset-l1"><br><br><br><br>
            <a class="perfil left bt bt_gray" href="<?php echo HOST;?>">Voltar</a>
        </div>
</section>
