<?php 
$breadColor = 'orange';
$breadPaths = array();
$lastPath = 'PIF';
include('top.phtml'); 

?>
       <div class="aug_grey_bg m-b-0">
		   <div class="image-background-text" style="background-image: url('img/pif.jpg'); position: relative;">
            <div class="gradiente"></div>
            <article class="col s12 l4 offset-l1 news-title">
                    <div class="heading upper aug_orange_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">PIF</div>
                    <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">Peritonite Infecciosa Felina</h2>
                    <h3 class="italic white-text text_10 col s12" style="margin-top: -20px;">A PIF é uma das doenças que mais assustam os donos de gatos, mas não é preciso entrar em pânico. Uma porcentagem muito pequena de gatos adquire a doença. A verdade é que todos os gatos, independentemente de onde vivem ou viveram (em casa, na rua ou em gatil) podem ter a doença em alguma fase da vida, e não temos muito como preveni-la.</h3>
            </article>
       </div>
	    	<article class="row container m-b-0 maxw-960">
	    	
	    		<div class="col s12" style="margin-top: 50px; margin-bottom: 50px;">
					<p class="text_10 m-b-10">A PIF é uma das doenças que mais assustam os donos de gatos, mas não é preciso entrar em pânico. Uma porcentagem muito pequena de gatos adquire a doença. A verdade é que todos os gatos, independentemente de onde vivem ou viveram (em casa, na rua ou em gatil), podem ter a doença em alguma fase da vida, e não temos muito como preveni-la.</p>
					<p class="text_10 m-b-10">O vilão da história se chama Coronavírus. É um vírus bastante comum, transmitido principalmente pelas fezes (o uso de uma mesma caixa de areia, por exemplo). Em contato com o Coronavírus, os gatos podem fazer uma mutação e manifestar PIF.</p>
					<p class="text_10 m-b-10">O fato de um gatinho ter sido exposto ao Coronavírus não significa que ele vai manifestar PIF. A maioria dos gatos é exposta pelo menos uma vez na vida e permanece saudável. Isso porque apenas alguns gatos fazem a mutação, varia de indivíduo para indivíduo.</p>
					<p class="text_10 m-b-10">A PIF é uma doença que acomete mais os filhotes, pois eles ainda estão em crescimento, em fase de desenvolvimento. Quando um adulto manifesta PIF geralmente é por uma queda de imunidade (após uma vacinação, uma cirurgia, uma doença, um trauma, etc.), mas eles são bem mais resistentes.</p>
					
				<div class="col s12 m5 text_15 pull-m1 m-t-20 m-b-20 text-right aug_orange" style="font-weight: lighter;"><em>A PIF é uma doença que acomete mais os filhotes, pois eles ainda estão em crescimento, em fase de desenvolvimento. Quando um adulto manifesta PIF geralmente é por uma queda de imunidade (após uma vacinação, uma cirurgia, uma doença, um trauma, etc.), mas eles são bem mais resistentes.</em></div>

					<h5 class="aug_orange m-b-10">Como saber quando o gatinho manifesta a PIF?</h5>

					<p class="text_10 m-b-10">Existem dois tipos: a seca e a úmida.</p>
					<p class="text_10 m-b-10">Na PIF úmida, o gatinho começa a juntar líquido na barriga (abdome ou tórax) devido a um processo inflamatório nos vasos. Eles têm febre e vão perdendo o apetite. Uma análise do líquido é capaz de dizer se ele está com PIF ou se pode ser alguma outra doença.</p>
					<p class="text_10 m-b-10">A PIF seca é de diagnóstico mais difícil. Formam-se granulomas e necroses em diversos órgãos do corpo. E os sintomas variam de acordo com o local onde o Coronavírus está atuando. É por isso que a PIF muitas vezes é confundida com outras doenças. Um problema no fígado, por exemplo, pode não ser primário e sim secundário à PIF.</p>
					<h5 class="aug_orange m-b-10">Dá para fazer algum exame para confirmar se meu gato tem PIF?</h5>
					<p class="text_10 m-b-10">Existe um teste de anticorpos que é feito para se detectar a PIF, mas é importante saber que ele não é conclusivo. Ele detecta a presença de anticorpos ao Coronavírus, ou seja, um gato saudável ou com outras doenças pode possuir esses anticorpos e não necessariamente ter PIF.</p>
					<p class="text_10 m-b-10">Para afirmar que um gato tem PIF é preciso associar os sintomas com o resultado de outros exames, como hemograma e relação albumina globulina (proteína). Certeza, certeza mesmo, só com a necropsia.</p>
					<h5 class="aug_orange m-b-10">A PIF não tem cura?</h5>
					<p class="text_10 m-b-10">Infelizmente não. É administrado um tratamento paliativo apenas. Esperamos que a ciência avance rapidamente e logo traga esperança para os gatinhos!</p>
					<p class="text_10 m-b-10">Importante: O texto que escrevemos é feito com base na nossa experiência com nossos gatinhos. Consulte um veterinário para mais informações</p>
				</div>
			</article>
		</div>