<?php 
$breadColor = 'purple';
$breadPaths = array();
$lastPath = 'Política de adoção';
include('top.phtml'); 

?>
<div class="aug_grey_bg m-b-0">
	<div class="image-background-text" style="background-image: url('img/politica-de-adocao.jpg'); position: relative;">
		<div class="gradiente"></div>
		<article class="col s12 l4 offset-l1 news-title">
			<div class="heading upper aug_purple_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">Política de Adoção</div>
			<h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">Política de Adoção</h2>
			<h3 class="italic white-text text_10 col s12" style="margin-top: -20px;">Adoções somente para São Paulo e ABC (Santo André, São Bernardo e São Caetano do Sul). Todos os gatinhos são doados castrados e vacinados.</h3>
		</article>
	</div>
	<article class="row container-large m-b-0 maxw-960">

		<div class="col m12" style="margin-top: 50px; margin-bottom: 50px;">

			<p class="m-b-10">Quase todos os nossos gatos chegam doentes, assustados, sujos e com muito medo. Na rua, eles experimentam do pior: desde a dor de serem abandonados por aquela pessoa em quem confiavam, até maus-tratos e envenenamentos. Todo mundo já ouviu histórias de alguém que maltratou um gatinho quando era criança ou mesmo quando adulto. O fato é que o gato ainda é um animal muito incompreendido e, infelizmente, o preconceito com relação a eles ainda é muito grande. </p>
			<p class="m-b-10">Na nossa opinião, lugar de gato é dentro de casa. Por isso, além de preencher o formulário de adoção, os candidatos a adotantes devem estar de acordo com a vistoria que será feita em sua casa antes da entrega do gatinho. </p>
			<p class="m-b-10">Gatinhos precisam de segurança. Para quem mora em apartamento, todas as janelas, varandas e basculantes devem ser teladas. Para quem mora em casa, os muros precisam ser altos e precisamos proteger portões, janelas e varandas.</p>
			
			<h5 class="bold upper aug_purple">Apartamentos</h5>

			<p class="m-b-10">Doamos os gatos para apartamentos com telas, em boas condições, fixas em todas as janelas, varandas, vitrôs e basculantes. Não aceitamos telas removíveis de nenhum tipo. As telas devem ser próprias para gatos, ou seja, com trama de no máximo 5cm. É importante que os ganchos que fixam as telas sejam colocados a uma distância aproximada de 20 a 25cm para evitar a formação de “barrigas”.</p>
			<p class="m-b-10">Caso as janelas basculantes não possam ser teladas, o adotante pode instalar limitadores, desde que fixos. </p>
			<p class="m-b-10"><strong class="aug_purple upper">IMPORTANTE:</strong> as telas têm validade de, no máximo, 5 anos e devem ser vistoriadas periodicamente. </p>
			<p class="m-b-10">Temos uma lista de empresas que fazem o serviço <a href="http://adoteumgatinho.org.br/telas-nas-janelas" class="bold upper aug_purple">aqui</a>.</p>

			<h5 class="bold upper aug_purple">Casas</h5>

			<p class="m-b-10">Casas precisam ser seguras (com muros bem altos, telas ou alguma barreira física que impeça a saída do gatinho para o telhado/rua). Não basta fechar as portas ou janelas, essa barreira física a mais precisa existir ou ser instalada.</p>
			
			<ul class="row col s12">
				<li class="m-b-10 aug_purple bold text_13 col s10 offset-s1">1) Na frente, se antes da porta/janela tiver um portão (ex: portão da garagem), este portão deve ser INTEIRO TELADO.</li>
				<li class="m-b-10 aug_purple bold text_13 col s10 offset-s1">2) Após o portão, havendo janelas, estas janelas devem ser INTEIRAMENTE TELADAS.</li>
				<li class="m-b-10 aug_purple bold text_13 col s10 offset-s1">3) Havendo janelas que dêem para a rua, seja no 1º andar ou no 2º andar, mesmo que altas, estas janelas devem ser INTEIRAS TELADAS.</li>
				<li class="m-b-10 aug_purple bold text_13 col s10 offset-s1">4) Havendo quintal, as janelas que dêem acesso ao telhado ou a muros, devem ser INTEIRAS TELADAS.</li>
			</ul>

			<p class="m-b-10">O gato não poderá ter qualquer acesso ao telhado/muros, muito menos à rua.</p>
			<p class="m-b-10">Ainda no caso de quintal, os muros do quintal devem ser BEM ALTOS, o suficiente para que seja impossível um gato escalar ou fugir. A medida deve ser no mínimo 2,50m.</p>
			<p class="m-b-10">Além de oferecer um lar seguro, os adotantes precisam ter condições financeiras para arcar com veterinário e ração de boa qualidade. No ato da adoção, a pessoa preenche e assina um contrato de adoção responsável no qual se compromete a:</p>

			<ul class="aug_purple bold col m-t-10 row s12 text_13">
				<li class="col s10 offset-s1 lista-texto m-t-20">mantê-lo dentro de casa, em segurança;</li>
				<li class="col s10 offset-s1 lista-texto m-t-20">oferecer comida adequada, além de água limpa e fresca;</li>
				<li class="col s10 offset-s1 lista-texto m-t-20">vaciná-lo anualmente;</li>
				<li class="col s10 offset-s1 lista-texto m-t-20">avisar ao voluntário responsável pela adoção caso tenha algum problema com a adaptação;</li>
				<li class="col s10 offset-s1 lista-texto m-t-20">devolvê-lo para a ONG caso não possa mais ficar com ele; e</li>
				<li class="col s10 offset-s1 lista-texto m-t-20">prestar assistência veterinária sempre que necessário. </li>
			</ul>

			
			<p class="m-b-10">Lembramos que cada gatinho tem um temperamento diferente e que procuramos adequar as necessidade de cada animal às necessidades dos adotantes.</p>


			<!-- <ul class="collection with-header">
				<li class="collection-header bold upper aug_purple text_15">Tipos de telas aceitos:</li>
				<li class="collection-item">De polietileno de alta densidade (polímero conhecido pela sigla PEAD). Suporta 500/600 kg de impacto por m². Essa rede possui “nós” entre as malhas.</li>
				<li class="collection-item">De aço ou metal;</li>
				<li class="collection-item">Alambrados fabricados em arame galvanizado (podendo ser revestido em PVC ou não).</li>
				<li class="collection-item">Do tipo galinheiro ou pet screen (desde que fixas, ou seja, chumbadas nas paredes).</li>
			</ul> -->

			<!-- <p class="m-b-10">No caso das casas, além do perigo das quedas, há também o perigo de fugas. É preciso ter muros altos, ou telas, ou dar algum jeitinho de eles não escaparem. Se necessário, modificar a estrutura da casa. Sim, porque gatos escalam tudo com a maior facilidade, e se bobear, eles saem para a rua num instante.</p>
			<p class="m-b-10">Na rua, além de serem alvo de acidentes e crueldades, eles também podem pegar doenças de outros animais. Existem doenças, como a FIV (aids), FELV (leucemia) e PIF (peritonite infecciosa felina), que são incuráveis.</p>

			<div class="col s12 m5 text_15 pull-m1 m-t-20 m-b-20 text-right aug_purple" style="font-weight: lighter;"><em>"Infelizmente, no Brasil o preconceito em relação aos gatos ainda é muito grande. Todo mundo já ouviu histórias de alguém que envenenou, atropelou de propósito, deu tiros de chumbinho, soltou o cachorro em cima, etc."</em></div>

			<p class="m-b-10">Se você não pode ou não quer prender o gatinho dentro de casa, recomendamos optar por outro animalzinho de estimação, como cachorros, que não escalam, nem pulam muros. Ficam para dentro do portão, longe dos perigos.</p>
			<p class="m-b-10">Estatísticas mostram que gatinhos que saem para a rua vivem em média 3 anos e gatinhos que ficam para dentro vivem 15.</p>
			<p class="m-b-10">No interior, na praia, em cidades tranquilas, gatinhos podem viver muitos anos passeando por aí. Mas em São Paulo, cidade grande, a chance de o pior acontecer logo é muito grande.</p>
			<p class="m-b-10">Gatos se adaptam muito bem ao espaço que lhe é oferecido, por isso não ache que é "maldade" deixar o gatinho do lado de dentro.</p>
			<p class="m-b-10">É um direito seu não concordar com nossa opinião sobre a qualidade de vida dos gatinhos. Neste caso, pedimos apenas respeito.</p>
			<p class="m-b-10">Não é de nosso interesse segurar a adoção dos gatinhos quando eles precisam de um lar.</p>
			<p class="m-b-10">Isso não quer dizer que você seja má pessoa ou que não saiba cuidar de um gatinho. Se a adoção é negada é porque julgamos melhor para o gatinho. Você pode adotar um gatinho com outras entidades, em sites de doação, feirinhas e outros locais. E cuidar dele como achar melhor.</p>
			<p class="m-b-10">Se você mora em apartamento ou casa todos os ajustes e instalações devem ser feitos antes da adoção.</p>
			<p class="m-b-10">Sim, fulano conhece alguém que tem um gato de 10 anos que nunca pulou. Gatos têm temperamentos diferentes e não gostamos de dar sorte para o azar. A maioria um dia escorrega ou se empolga com um passarinho, cai e morre.</p>
			<p class="m-b-10">Gastamos fortunas com tratamentos, vacinas, castrações, nos apegamos a eles e os tratamos como nossos filhos. Para a gente, eles não são um número, cada gatinho tem muito valor.</p>
			<p class="m-b-10">Já sofremos bastante com algumas adoções "erradas" no início de nosso trabalho e, podemos até pecar por excesso de zelo (e às vezes pecamos mesmo, infelizmente), mas é por amá-los demais que nos tornamos tão criteriosas.</p>
			<p class="m-b-10">Por se tratar de um site de adoção <strong class="aug_purple">GRATUITA</strong>, muita gente nos ofende, pensando que estão nos fazendo um favor em adotar os gatinhos e que temos obrigação de doá-los para quem os queira.</p>
			<p class="m-b-10">Não é assim que encaramos.</p>
			<p class="m-b-10">Não temos pressa. Prezamos pela qualidade ao invés da quantidade de gatinhos adotados.</p>
			<p class="m-b-10">Requisitos para adotar um gatinho do Adote um Gatinho:</p>
			<div class="col s12 m11 offset-m1 text_13 m-t-20 m-b-20 aug_purple" style="font-weight: lighter;">
				<p class="offset-s1">1) morar em casa ou apartamentos "seguros"</p>
				<p class="offset-s1">2) ter condições financeiras para arcar com veterinário e ração de boa qualidade</p>
			</div>

			<p class="m-b-10">Também poderão ser analisados itens como alergia, gravidez, crianças em casa, outros animais em casa, o tempo em que o animal ficará sozinho durante o dia, etc..</p>
			<p class="m-b-10">Lembramos que cada gatinho tem um temperamento diferente e que procuramos adequar as necessidade de cada animal às necessidades dos adotantes.</p> -->

		</div>
	</article>
</div>