<?php 
$breadColor = 'purple';
$breadPaths = array();
$lastPath =  'Preparado para adotar';
include('top.phtml'); 

?>
   <div class="aug_grey_bg m-b-0">
		   <div class="image-background-text" style="background-image: url('img/preparado-para-adotar.jpg'); position: relative;">
            <div class="gradiente"></div>
            <article class="col s12 l4 offset-l1 news-title">
                    <div class="heading upper aug_purple_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">Informações Importantes</div>
                    <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">Estou preparado para adotar?</h2>
                    <h3 class="italic white-text text_10 col s12" style="margin-top: -20px;">O que é posse responsável? É ter a guarda de um bichinho e não lhe deixar faltar nada. É zelar por sua saúde, sua alimentação, amor e segurança. É respeitá-lo, respeitar suas características e seus hábitos, e ser um verdadeiro guardião.</h3>
            </article>
       </div>
	    	<article class="row container m-b-0">
	    	
	    		<div class="col m10 offset-m2" style="margin-top: 50px; margin-bottom: 50px;">

	    		<p class="m-b-10">Se você pretende ter um gatinho ou outro bichinho de estimação, precisa pensar em alguns pontos fundamentais. Bicho não é brinquedo. É uma vida e você será responsável por ela por muitos e muitos anos.</p>
	    		
	    		<h5 class="bold aug_purple">1) Dinheiro</h5>
	    		<p class="m-b-10">Não basta dar comida e amor para o seu gatinho. Você precisa estar preparado financeiramente para as despesas com veterinário. Isso inclui: vermífugos, antipulga e vacinas periodicamente e castração uma vez na vida.</p>
	    		<p class="m-b-10">Sem falar que de vez em quando seu gatinho poderá ficar doente e o tratamento nem sempre será barato. Esteja preparado para doenças e emergências veterinárias. Se preciso, faça uma poupança. Você sabe quando irá ficar doente? Os gatos também não…</p>
	    		
	    		<h5 class="bold aug_purple">2) Vermífugos e antipulga</h5>
	    		<p class="m-b-10">É preciso controlar pulgas e vermes periodicamente, pois um está ligado ao outro. A pulga transmite vermes ao gato, então nunca deixe que ele tenha pulgas. Importante: quem tem pulgas é o ambiente, ou seja, se o seu gatinho tiver pulga, é sinal de que a sua casa está com pulgas.</p>
	    		<p class="m-b-10">Para mais informações sobre pulgas, acesse <a href="https://www.bayerpet.com.br/gatos/parasitas-zoonoses/pulgas/#o-parasita" target="_blank" class="aug_purple bold upper truncate">https://www.bayerpet.com.br/gatos/parasitas-zoonoses/pulgas/#o-parasita</a></p>
	    		
	    		<h5 class="bold aug_purple">3) Vacinas</h5>
	    		<p class="m-b-10">Os filhotes devem tomar a primeira dose da vacina Quádrupla Felina aos 60 dias, a segunda dose aos 90 e a terceira dose aos 120 dias, quando deverá receber também a vacina antirrábica. Depois, basta repetir uma dose de cada vacina de ano em ano.</p>
	    		
	    		<h5 class="bold aug_purple"> 4) Castração</h5>
	    		<p class="m-b-10">Todos os gatos resgatados pelo Adote um Gatinho são castrados. A castração não serve só para evitar que nasçam filhotes. Ao serem esterilizados, os animais tendem a ficar mais tranquilos e deixam de brigar, ou seja, correm menos risco de serem infectados por doenças transmitidas pelo ato sexual e por mordidas.</p>
				<p class="m-b-10">Outros problemas de comportamento como, por exemplo, a necessidade de urinar para demarcar território, são reduzidos ou eliminados. O risco dos animais desenvolverem certos cânceres em idade avançada é bastante reduzido com a esterilização. </p>
				<a href="http://www.adoteumgatinho.com.br/a-importancia-da-castracao" class="upper aug_purple_bg white-text bold" style="padding: 2px 15px; display: inline-block;">Saiba mais clicando aqui</a>
	    		
	    		<h5 class="bold aug_purple"> 5) Segurança</h5>
	    		<p class="m-b-10">Gatos são muito curiosos e podem tentar pegar insetos, pássaros ou objetos fora do apartamento. Muita gente acha que é besteira, mas realmente acontece de o gatinho cair e morrer. Quer um exemplo?</p><a href="http://www.adoteumgatinho.com.br/redes" class="upper aug_purple_bg white-text bold m-b-10" style="padding: 2px 15px; display: inline-block;">Clique aqui.</a>


				<p class="m-b-10">Tutores responsáveis querem sempre o melhor para seus gatinhos e isso inclui a sua segurança. Apartamentos devem ter redes de proteção em todas as janelas, sacadas, vitrôs e basculantes. É importante verificar as telas periodicamente para ver se estão de fato seguras. Elas têm validade de 3 a 5 anos e precisam ser trocadas. </p>
				<p class="m-b-10">Se você mora em casa, além do perigo das quedas existe o perigo das fugas. Lugar de gato não é na rua e nem em cima do telhado.</p>
				<p class="m-b-10">Ah, o gato passeia e depois volta. Até o dia que não volta mais, né?</p>
				<p class="m-b-10">Gatos indoor vivem em média 12 anos, enquanto os que têm acesso a rua vivem apenas 3. Nossos gatinhos são animais sofridos, que já passaram pelo pior. Desejamos que eles não corram mais riscos desnecessários de serem atropelados, maltratados, envenenados, se percam ou peguem doenças na rua.</p>
				<p class="m-b-10">Se você mora em casa, cuide para que ela seja à prova de fugas. Ou seja, tenha muros altos e telas em todas as saídas e acessos a rua e telhados. Você pode não concordar e achar que lugar de gato é solto, mas não passará na avaliação do Adote um Gatinho e não poderá adotar com a ONG.</p>

	    		<h5 class="bold aug_purple">6) Amigo para a vida toda</h5>
	    		<p class="m-b-10">Os gatos podem viver até uns 18 anos ou mais! Ao adotar um bichinho, você assume o compromisso de cuidá-lo e protegê-lo por todo esse tempo. Animais de estimação não são descartáveis, nem brinquedo. Devem ser, sempre, parte da família.</p>
	    		<p class="m-b-10">Se você e sua família costumam viajar, deixe o seu gatinho em um hotel específico para gatos ou contrate o serviço de catsitter de alguém de confiança. </p>
				
				<h5 class="bold aug_purple">7) Alimentação</h5>
				<p class="m-b-10">Alimente seu animal com uma ração de boa qualidade e adequada à sua idade. Os gatos comem pequenas porções várias vezes ao dia. Por isso, recomendamos que você deixe a ração à disposição do bichinho para quando ele quiser comer. </p>
				<p class="m-b-10">Os nossos gatinhos só comem ração da Royal Canin, considerada “super premium”, ou seja, de melhor qualidade. Investir em uma ração boa pode parecer caro em um primeiro momento, mas ela evita muitos problemas de saúde e faz com que os tutores gastem menos com veterinário. Há outras vantagens em comprar essas rações “super premium”: os gatos precisam comer menos e fazem menos cocô, mais durinho e menos fedido. </p>
				<p class="m-b-10">Gatos adoram tomar água limpa. É preciso trocar sempre, pois, como dissemos, são animais muito higiênicos. Prefira os potes de vidro ou alumínio e, se possível, invista em uma fonte. Afinal, muitos gatos gostam de beber água corrente. Para ajudar a evitar problemas renais, típicos dos gatos, tenha potes em lugares estratégicos da casa por onde o gatinho passa. </p>
				
				<h5 class="bold aug_purple">8) Caixa de areia </h5>
				<p class="m-b-10">Os gatos aprendem sozinhos a usar a caixinha de areia. Você não vai precisar ensiná-lo.</p>
				<p class="m-b-10">A areia é encontrada em todos os pet shops e também em supermercados.</p>
				<p class="m-b-10">Importante: não coloque a comida do gato e a água perto da caixa. Os gatos são muito limpos e detestam comer perto de seu cocô e xixi.</p>

				<h5 class="bold aug_purple">9) Companhia </h5>
				<p class="m-b-10">Os animais sentem tristeza assim como os humanos e muitos sofrem de depressão.</p>
				<p class="m-b-10">Se você trabalha fora o dia todo e quer um bichinho para lhe fazer companhia, o gato é a melhor opção, mas procure optar sempre por dois ao invés de um. Os gastos e o trabalho são praticamente os mesmos e eles poderão dormir e comer juntos, um fazendo companhia para o outro. Gatos dormem muitas horas, portanto se adaptam melhor à ausência do dono, mas não é raro ver um gatinho filho único deprimido, com manias para chamar a atenção.</p>
				<p class="m-b-10">Todos os dias pessoas que têm apenas um gatinho escrevem para o site para adotar um irmãozinho para ele. Por isso, adote dois logo de cara.</p>

				<h5 class="bold aug_purple">10) Crianças </h5>
				<p class="m-b-10">Se o seu filho quer um animalzinho mas ainda é muito pequeno, então lhe dê um bichinho de pelúcia e continue incentivando o amor pelos animais, até que ele esteja maduro para poder se responsabilizar pelo animal e tratá-lo bem.</p>

				<h5 class="bold aug_purple">11) Adulto X Filhote </h5>
				<p class="m-b-10">Se você não tem tempo ou paciência para criar um filhote, que é mais brincalhão e exige mais cuidados, adote um animal adulto. Você já saberá que personalidade ele tem e poderá escolher um que se encaixe com o seu perfil.</p>

				<h5 class="bold aug_purple">12) Transporte </h5>
				<p class="m-b-10">Os gatos não devem ser transportados no colo ou com coleiras porque podem se assustar, arranhar, fugir ou até mesmo provocar um acidente. Eles precisam de uma caixinha de transporte segura e feita especialmente para eles. Existem vários modelos à venda em pet shops.</p>

				<h5 class="bold aug_purple">13) Ronronar </h5>
				<p class="m-b-10">O gato ronrona para mostrar que está feliz e confortável. Em casos raros, o gato ronrona também quando está com dor ou para pedir socorro.</p>

				<h5 class="bold aug_purple">14) Unhas e arranhador </h5>
				<p class="m-b-10">Existem tesourinhas próprias para cortar a unha dos gatos. Preste atenção para cortar somente a pontinha e jamais corte a parte rosa! Se tiver dúvida, peça orientação ao veterinário. </p>
				<p class="m-b-10">Compre um arranhador e ensine o seu gato a usá-lo desde pequeno. Isso evitará danos maiores ao sofá, mas não pense que os gatos vão deixar de afiar as unhas nos móveis e nem se desespere por não ter conseguido educá-los. Eles adoram fazer isso e vão continuar arranhando, SIM! Ao comprar um sofá, escolha um tecido que não estrague tanto. </p>

				<h5 class="bold aug_purple">15) Brincadeiras </h5>
				<p class="m-b-10">Muita gente adota um gato e espera que ele se comporte como um cachorro. Isso é errado! São espécies diferentes e cada um tem seu jeito de ser. Os gatos adoram brincar de morder e arranhar. Adoram bolinhas de papel e brinquedos com catnip, a erva do gato. Tente essas brincadeiras e você vai rolar de rir! Cuidado com fiozinhos: muitos gatinhos acabam engolindo os fios e precisam de cirurgia para tirá-los. </p>

				<h5 class="bold aug_purple">16) Camas </h5>
				<p class="m-b-10">Os gatos gostam de lugares limpos e macios. Quanto mais fofinho, melhor.</p>
				<p class="m-b-10">A caminha pode ser de espuma, própria para gatos, mas também pode ser uma cestinha de vime ou de palha, forrada com um cobertorzinho, ou ainda uma caixinha de papelão.</p>

				<h5 class="bold aug_purple">17) Banhos </h5>
				<p class="m-b-10">Gatos normalmente não precisam de banho. O gato é muito limpo e higiênico por natureza.</p>

				<h5 class="bold aug_purple">18) Escovação </h5>
				<p class="m-b-10">Gatos adoram ser escovados. E é muito bom para eles, pois escovar retira o excesso de pêlos que eles normalmente lambem e engolem.</p>

				<h5 class="bold aug_purple">19) Caça </h5>
				<p class="m-b-10">Por mais cruel que pareça, se o seu gato te levar um passarinho, uma borboleta, lagartixa ou rato na boca, ele estará simplesmente tentando te agradar. É um presente que ele estará te oferecendo.</p>

				<h5 class="bold aug_purple">20) Coleiras </h5>
				<p class="m-b-10">Gatos ficam lindinhos com coleiras, mas muito cuidado na hora de escolher. Como eles são ágeis, escalam, pulam, se enfiam em buracos, a chance de se enforcarem é grande. Se quiser colocar uma coleira, escolha as de elástico e tire o guizo. </p>

				<h5 class="bold aug_purple">21) Intoxicação</h5>
				<p class="m-b-10">Muito cuidado com produtos de limpeza, que podem provocar intoxicação e alergia em seu bichinho. Também cuidado com plantas tóxicas, como a comigo-ninguém-pode e algumas samambaias. Temos um álbum com fotos das plantas perigosas para os gatinhos:</p>
				<a href="https://www.facebook.com/media/set/?set=a.10154370394881314.1073741858.130323036313&type=1&l=72d40c3fbb" target="_blank" class="upper aug_purple_bg white-text bold m-b-10" style="padding: 2px 15px; display: inline-block;">Clique aqui.</a>

			    <div class="col s12">
				    <ul class="collection with-header">
				        <li class="collection-header bold upper aug_purple text_15">O que é preciso ter para a chegada do meu gatinho</li>
				        <li class="collection-item">Caixa sanitária e areia</li>
				        <li class="collection-item">Caixa de transporte</li>
				        <li class="collection-item">Comedouro </li>
				        <li class="collection-item">Ração</li>
				        <li class="collection-item">Caminha e cobertor</li>
				        <li class="collection-item">Arranhador</li>
				        <li class="collection-item">Brinquedos</li>
				    </ul>
				</div>

				<div class="col s12 m6 hide-on-small-only">
					<div class="card white card-wrapper m-b-10 col s12" align="center" style="padding: 3rem;">
						<div class="card-title aug_purple bold text_15 m-b-10 upper" style="background-color: transparent; text-shadow: none;">NÃO DÊ ANIMAIS DE PRESENTE! </div>
						<p class="m-t-10">Não imponha um animal a quem não fez uma escolha consciente de adotá-lo. Animais não são objetos!</p>
					</div>
				</div>
				
				<div class="col s12 m6 hide-on-small-only">
					<div class="card white card-wrapper m-b-10 col s12" align="center" style="padding: 3rem;">
						<span class="card-title aug_purple bold text_15 m-b-10 upper" style="background-color: transparent; text-shadow: none;">NÃO COMPRE ANIMAIS</span>
						<p class="m-t-10">Além de você tirar a chance de um animalzinho de rua ganhar uma casa, você está estimulando o comércio indiscriminado de VIDAS. Sim, VIDAS não têm preço. Animais não são objetos. Não alimente o sustento de quem faz uma gatinha ou uma cadelinha parir a vida inteira para encher o bolso de dinheiro.</p>
					</div>
				</div>


				<div class="col s12 m6 hide-on-med-and-up">
					<div class="card white card-wrapper m-b-10 col s12" align="center" style="padding: 3rem;">
						<div class="card-title aug_purple bold text_15 m-b-10 upper" style="background-color: transparent; text-shadow: none;">NÃO DÊ ANIMAIS DE PRESENTE! </div>
						<p class="m-t-10">Não imponha um animal a quem não fez uma escolha consciente de adotá-lo. Animais não são objetos!</p>
					</div>
				</div>
				
				<div class="col s12 m6 hide-on-med-and-up">
					<div class="card white card-wrapper m-b-10 col s12" align="center" style="padding: 3rem;">
						<span class="card-title aug_purple bold text_15 m-b-10 upper" style="background-color: transparent; text-shadow: none;">NÃO COMPRE ANIMAIS</span>
						<p class="m-t-10">Além de você tirar a chance de um animalzinho de rua ganhar uma casa, você está estimulando o comércio indiscriminado de VIDAS. Sim, VIDAS não têm preço. Animais não são objetos. Não alimente o sustento de quem faz uma gatinha ou uma cadelinha parir a vida inteira para encher o bolso de dinheiro.</p>
					</div>
				</div>
				
				</div>
			</article>
		</div>