<?php
$breadColor = 'blue';
$breadPaths = array();
$lastPath = 'Como posso ajudar?';
include('top.phtml');
?>

        <div class="aug_grey_bg m-b-0">
            <div class="image-background-text" style="background-image: url('<?php echo HOST; ?>__novo/img/ajudar.jpg'); position: relative; background-position: right;">
            <div class="gradiente"></div>
                <div class="col s12 l4 offset-l1 news-title">
                        <div class="heading upper aug_blue_bg white-text bold m-t-20" style="padding: 2px 15px; display: inline-block;">Quero Ajudar</div>
                        <h2 class="bold upper white-text h1 responsive" style="margin-top: 13px; display: block;">COMO POSSO AJUDAR?</h2>
                        <h3 class="italic white-text text_10 col s12" style="margin-top: -20px;">Temos muitos gatinhos que precisam de ajuda. Veja aqui como você pode nos ajudar!</h3>
                </div>
            </div>
            <section class="row container m-b-0">

              <article class="col s12 m-t-0" style="margin-top: 50px; ">
                <h4 class="text_15 bold upper aug_blue m-t-0 m-b-10 text-center">Campanha Doe um Tijolinho</h4>
                <div class="col s12">
                  <p><br>Como os gatinhos moram de aluguel, começamos a juntar dinheiro para comprar uma sede. Abrimos uma poupança em 2015 e estamos arrecadando doações para concretizar esse sonho desde então. Por mais que demore, a gente sabe que uma hora vai dar certo!</p>
                  <p><br>Para ajudar, faça um depósito em qualquer valor na conta a seguir: </p>
                </div>
                <div class="col s12">
                  <div class="row  m-t-20">
                      <div class="container text-center">
                          <div class="col s12 card white card-wrapper m-b-20" style="padding: 3rem; display: inline-block;">
                              <h4 class="aug_blue bold text_10 m-b-10 m-t-0 upper" style="background-color: transparent; text-shadow: none;">CONTA DOS GATINHOS DO AUG</h4>
                              <p class="bold aug_blue m-t-10">Razão Social: Adote um Gatinho</p>
                              <p class="m-b-10"><strong>CNPJ:</strong>08.858.329/0001-08</p>
                              <div class="m-t-10" style="display: inline-block;">
                                  <p><strong>Itaú:</strong> 0341</p>
                                  <p><strong>Agência:</strong> 2970</p>
                                  <p><strong>C/C:</strong> 23293-6</p>
                              </div>
                          </div>
                      </div>
                  </div>
                </div>


              </article>

                <div class="col s12 m-b-0" style="margin-top: 50px; margin-bottom: 50px;">
                    <p class="text_10 m-t-0">Quando cuidávamos de um punhadinho de gatos, já tínhamos dificuldade, mas nós dávamos conta de bancar com dinheiro do nosso próprio bolso as vacinas, castrações, tratamentos e alimentação dos gatinhos. </p>
                    <p class="text_10 m-t-10">Aos poucos, as pessoas foram se interessando pelo nosso trabalho e começaram a nos ajudar. Fomos tirando mais e mais gatinhos das ruas. Hoje, todo o trabalho do Adote Um Gatinho não seria possível sem as doações e sem a ajuda de pessoas maravilhosas que contribuem regular ou esporadicamente com o nosso trabalho. </p>
                    <p class="text_10 m-t-10">Temos medo que o dinheiro falte e que nossos gatinhos passem por dificuldades, até porque jamais daríamos conta dessa turma toda sozinhos. E é por isso que as doações em ração, dinheiro e produtos são essenciais à manutenção e continuidade do nosso trabalho. Afinal, ainda não contamos com patrocínio de nenhuma empresa. </p>
                    <p class="text_10 m-t-10">Ajude os gatinhos do Adote Um Gatinho! Dê uma olhada na lista abaixo e nos ajude com o que estiver ao seu alcance. Toda ajuda é bem-vinda!</p>
                </div>

                <div class="col s12 m-t-0">
                    <h4 class="text_15 bold upper aug_blue m-t-0 m-b-10 text-center">Doações em dinheiro</h4>
                    <p>O dinheiro que recebemos é usado para pagarmos por cirurgias (inclusive as de castração), tratamentos, internações, compra de vacinas e de tudo o que os gatinhos precisam. Consideramos o tipo de doação mais importante!</p>
                    <div class="row">
                        <div class="container">
                            <div class="col s12 card white card-wrapper m-b-20 m-t-20" style="padding: 3rem; display: inline-block;">
                                <h4 class="aug_blue bold text_10 m-b-10 m-t-0 upper text-center" style="background-color: transparent; text-shadow: none;">CONTAS DOS GATINHOS AUG</h4>

                                <p class="bold aug_blue m-t-10 text-center">Razão Social: Adote um Gatinho</p>
                                <p class="m-b-10 text-center"><strong>CNPJ:</strong>08.858.329/0001-08</p>

                                <div class="m-t-10" style="display: inline-block;">
                                    <p><strong>Itaú:</strong> 0341</p>
                                    <p><strong>Agência:</strong> 2970</p>
                                    <p><strong>C/C:</strong> 12869-6</p>
                                </div>
                                <div class="m-t-10 text-right hide-on-small-only" style="display: inline-block; float: right;">
                                    <p><strong>Bradesco:</strong> 0237</p>
                                    <p><strong>Agência:</strong> 3334</p>
                                    <p><strong>C/C:</strong> 6253-7</p>
                                </div>
                                <div class="m-t-10 hide-on-med-and-up">
                                    <p><strong>Bradesco:</strong> 0237</p>
                                    <p><strong>Agência:</strong> 3334</p>
                                    <p><strong>C/C:</strong> 6253-7</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="m-b-10">Se você preferir emitir um boleto, fazer transferência para contas de outros bancos ou pagar com cartão de crédito, estamos cadastrados no sistema PAGSEGURO, do UOL, que permite que você faça sua doação com segurança. Esse sistema nos cobra uma pequena porcentagem, por isso a doação não é 100% aproveitada pelos gatinhos. De qualquer forma, é uma maneira muito fácil e prática de ajudar sem sair de casa.</p>

                  <!--   <div class="video-container m-b-10">
                        <object id="player_12866592" width="457" height="368" data="http://player.mais.uol.com.br/embed_v2.swf?mediaId=12866592&amp;ver=1" type="application/x-shockwave-flash"><param name="allowfullscreen" value="true"><param name="allowscriptaccess" value="always"><param name="wmode" value="window"><param name="src" value="http://player.mais.uol.com.br/embed_v2.swf?mediaId=12866592&amp;ver=1"><noscript>&lt;a href="http://tvuol.uol.com.br/assistir.htm?video=12866592"&gt;Adote um Gatinho usa o PagSeguro para receber doações&lt;/a&gt;</noscript></object>
                    </div> -->

                    <p class="m-b-10">As taxas cobradas pelo PagSeguro são:</p>

                    <div class="col s12 p-0" id="container-card">
                        <ul class="m-b-10 collection col s12 m8 offset-m2 l6 offset-l3 p-0">
                            <li class="collection-item"><span class="bold aug_blue">Recebimentos à vista</span> <br>
                            (TEFs e Boletos)    <strong style="float: right; margin-top: -11px;">0,9%</strong></li>
                            <li class="collection-item"><span class="bold aug_blue"> Recebimentos a prazo</span> <br>
                            (cartão de crédito) <strong style="float: right; margin-top: -11px;">4,59%</strong></li>
                        </ul>
                    </div>

                    <p class="m-b-10 col s12" >Clique no botão abaixo e faça sua doação:</p>

                    <form action="https://pagseguro.uol.com.br/checkout/v2/donation.html" method="post" target="pagseguro" class="col s12 m-t-10 m-b-10" id="pagseguro">
                        <input type="hidden" name="receiverEmail" value="susan@adoteumgatinho.org.br" />
                        <input type="hidden" name="currency" value="BRL" />
                        <input type="image" name="submit" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/doacoes/94x52-doar-assina.gif" alt="Pague com PagSeguro - &eacute; r&aacute;pido, gr&aacute;tis e seguro!" />
                    </form>

                    <p class="m-b-10">Por favor, não deixe de nos avisar o dia e o valor da sua doação mandando um e-mail para <a href="mailto:informacoes@adoteumgatinho.org.br" class="aug_blue bold truncate">informacoes@adoteumgatinho.org.br</a>.</p>

                </div>







                <div class="m-t-0 col s12">
                    <h4 class="text_15 bold upper aug_blue m-t-0 m-b-10 text-center">Doando sua NF Paulista</h4>
                    <p class="m-b-10">Agora vocês mesmos fazem a doação das notas fiscais para nós, seja pelo site ou pelo aplicativo oficial da Nota Fiscal Paulista. Existem duas formas de doar: doações com CPF (automáticas, ou seja, sempre que o seu CPF for inserido na hora da compra, a doação será feita para nós) ou doações sem CPF (manuais, ou seja, a cada doação você precisa inserir os dados da nota fiscal).</p>
                    <p class="aug_blue bold">Vejam como fazer a doação automática:</p>
                    <p class="m-b-10"><b>1) Pelo site - https://www.nfp.fazenda.sp.gov.br/</b> <br>
Entidades > Doação com CPF (automática) > Pesquisar Entidade > CNPJ 08.858.329/0001-08 – Adote Um Gatinho > Confirmar Doação Automática;</p>

<p class="m-b-10"><b>2) Pelo app da Nota Fiscal Paulista</b> <br>
Doação Cupom com CPF > Selecione uma entidade > Adote Um Gatinho > Confirmar Doação Automática </p>

                    <p></p>
                    <p class="m-b-10"><span class="aug_orange bold upper">IMPORTANTE!</span> Nunca forneça o nosso CNPJ no ato da compra, pois assim você inviabiliza o uso desta nota fiscal. Precisando de mais alguma informação, é só falar com a gente!</p>
                </div>

                 <div class="col s12 m-t-0">
                    <h4 class="text_15 bold upper aug_blue m-t-0 m-b-10 text-center">Doações em produtos</h4>
                    <p class="m-b-10">Aceitamos doações de ração, areia, remédios, caminhas, arranhadores, caixas de transporte e cobertores. Para saber como entregar sua doação pessoalmente, escreva para <a href="mailto:informacoes@adoteumgatinho.org.br" class="aug_blue bold truncate">informacoes@adoteumgatinho.org.br</a>. </p>
                    <p class="m-b-10">Após a compra, envie um e-mail para informacoes@adoteumgatinho.org.br. Assim podemos conferir a entrega e colocar o seu nome na prestação de contas do site.</p>
                </div>
                 <div class="col s12 m-t-0">
                    <h5 class="heading upper aug_blue_bg white-text bold m-t-20 text_10 m-b-20" style="padding: 2px 15px; display: inline-block;">Produtos que sempre precisamos</h5>

                    <ul class="collection">
                        <li class="collection-item"><span class="text_15 bold aug_blue">Remédios veterinários:</span><br>
                            <strong>1. Comprimidos/cápsulas: </strong>Enropet, Baytril ou Zelotril 50mg, Baytril l15mg, Zitrex 100, Doxy 100, Doxy Suspensão, Doxitrat 80, Sinulox ou Agemoxi 50mg, Stomorgil 2mg, Stomorgil 10mg, Tramadol 12mg, Meticorten 5mg, ITL 25mg, ITL 50mg, Giardicid 50mg, Maxicam 0,5mg, Petprazol, Cerênia, Fortekor 5.
                            <br>
                            <strong>2. Colírio: </strong>Ciprovet
                            <strong>3. Solução/suspensão/gotas: </strong>Acepran, Natalene, Panalog, Epiotic.
                            <br>
                            <strong>4. Solução/suspensão: </strong>Ranitidina, Complexo B, Gentamicina, Metoclopramida, Ornitagin, Cerenia, Soro fisiológico, Ringer Lactato, Ioimbina, Lanthus Solostar (caneta), fenobarbital, Vitamina B12, Vitamina C, Isacort, Predi Medrol, Depo Medrol, Shotapen.
                            <br>
                            <strong>5. Pomadas: </strong>Cicatrilex, Vulketan, Alantol, Vetaglos.
                        </li>
                        <li class="collection-item">
                            <span class="text_15 bold aug_blue">Remédios humanos:</span><br>
                            <strong>1. Comprimidos/cápsulas: </strong>Cobavital, Metronidazol, Legalon 70, Secnidazol, Floratil 100, Predsim, Revimax 50mg
                            <br>
                            <strong>2. Colírios: </strong>Tobramicina, Tobradex, Maxitrol, Pred Fort, Cetrolac
                            <br>
                            <strong>3. Solução/suspensão/gotas: </strong>Terramicina pomada oftálmica, Epitezan pomada oftálmica, Omcilon orabase
                            <br>
                            <strong>4. Solucão/suspensão: </strong>Leucogen, Amoxicilina, Azitromicina, Fluimucil, Rinofluimucil, Rinosoro, Gardenal, Dipirona Sódica, Predsim, Nujol (óleo mineral)
                            <br>
                            <strong>5. Ampolas: </strong>Fluimucil, Ranitidina, Complexo B, Metoclopramida, Ampicilina, Ondasentrona, Tramadol
                            <br>
                            <strong>6. Diversos: </strong>Same, Itraconazol, Amitriptilina, Betanecol, Mitarzapina, Eritrpoeytina, Omeprazol, Amoxicilina com Clavulanato
                        </li>
                        <li class="collection-item">
                            <span class="text_15 bold aug_blue">Descartáveis:</span><br>
                            Seringas de 1, 3, 5, 10 e 20ml, seringas de insulina, equipos, agulhas, abaixador de língua, luvas, fita crepe, esparadrapo, algodão, gaze, atadura, tapetes higiênicos e scalps..
                        </li>
                        <li class="collection-item">
                            <span class="text_15 bold aug_blue">Papelaria e limpeza</span><br>
                            Papel sulfite, Cartuchos HP 92, 93, 662, post-it, pastas L, álcool 70%, clorexidine 2%, Vet + ou Herbalvet, água sanitária, desinfetante, detergente, sabão em pó e sacos de lixo de 60 litros reforçados.
                        </li>
                    </ul>
                </div>
                <div class="col s12">
                    <h4 class="text_15 bold upper aug_blue">Outras formas de ajudar</h4>
                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Apadrinhando um gatinho</span>
                        <p class="m-b-10 m-t-10">Seja madrinha ou padrinho dos nossos gatinhos.</p>
                        <p class="m-b-10">Você faz uma contribuição fixa mensal, ajuda a pagar pelas despesas do gatinho escolhido e recebe cartinhas com as novidades sobre ele!</p>
                         <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.adoteumgatinho.com.br/apadrinhamento" target="_blank">Clique Aqui</a>
                         </div>

                    </div>
                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue_btn aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Comprando na nossa lojinha</span>
                        <p class="m-b-10">Os produtos da marca Adote Um Gatinho têm 100% do lucro revertido para os nossos protegidos. </p>
                        <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.auglojinha.com.br/" target="_blank">Clique Aqui</a>
                        </div>
                    </div>
                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Divulgando o nosso trabalho</span>
                        <p class="m-b-10">Imprima um folheto do AUG e coloque em murais de pet shops e clínicas veterinárias.</p>
                        <p class="m-b-10">Curta e compartilhe nossos posts nas redes sociais:</p>
                            <div class="card-bottom multiple-links">
                                <p class="col s4 m-t-20" style="text-align: center;"><a href="https://www.facebook.com/adoteumgatinho/" target="_blank" class="aug_blue bold upper">Facebook</a></p>
                                <p class="col s4 m-t-20" style="text-align: center;"><a href="https://www.instagram.com/adoteumgatinho/" target="_blank" class="aug_blue bold upper">Instagram</a></p>
                                <p class="col s4 m-t-20" style="text-align: center;"><a href="https://twitter.com/AdoteUmGatinho/" target="_blank" class="aug_blue bold upper">Twitter</a></p>

                            </div>
                        </div>
                    </div>
                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Comprando no site da Pet Love</span>
                        <p class="m-b-10">Faça as suas compras pelo link a seguir e ajude os gatinhos do AUG</p>
                        <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.petlove.com.br/?utm_source=adote-um-gatinho&utm_medium=afiliados" target="_blank">Clique Aqui</a>
                        </div>
                    </div>
                    <div class="col s12 m6 l4 hide-on-small-only">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Utilizando os serviços do Pet Memorial</span>
                        <div style="height: 50%; overflow-y: auto;">
                            <p>A gente sempre espera que você não precise, mas caso você opte pela cremação, ao ligar para o Pet Memorial você pode ajudar os nossos gatos. Basta dizer que foi indicado pelo Adote um Gatinho e você estará contribuindo com R$50 ou R$100 (dependendo do plano escolhido). A promoção vale para os planos preventivos também.</p>
                            <p class="m-b-10 bold aug_blue">Telefone: 0800 772 8885 </p>
                        </div>
                        <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.petmemorial.com.br/" target="_blank">Clique Aqui</a>
                        </div>
                    </div>


                    <div class="col s12 m6 l4">
                        <div class="small card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Fazendo assinatura de ração no PetsdoBem</span>
                        <div style="height: 50%; overflow-y: auto;">
                           <p>O PetsdoBem é um delivery mensal de ração para gatos e cães! A cada 10kg de ração que você compra, recebemos 1kg para os nossos gatinhos, sem custo nenhum para você! </p>
                        </div>
                        <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.petsdobem.com.br " target="_blank">Clique Aqui</a>
                        </div>
                    </div>

                    <div class="col s12 m6 l4 hide-on-med-and-up">
                        <div class="large card card-wrapper p-10"><span class="card-title bold aug_blue aug_blue bold text_15" style="text-shadow: none; background-color: transparent;">Utilizando os serviços do Pet Memorial</span>
                        <div>
                            <p>A gente sempre espera que você não precise, mas caso seu bichinho (gato, cachorro, coelho, passarinho, cavalo, etc) partir para o céu e você optar pela cremação, ao ligar para a vendedora Marcia do Pet Memorial você pode ajudar o AUG. Basta  dizer que foi indicado pelo Adote um Gatinho você estará contribuindo com R$50 ou R$100 (dependendo do plano escolhido). A promoção vale para os planos preventivos também. </p>
                            <p class="m-b-10 bold aug_blue">Telefone: 0800 772 8885 </p>
                        </div>
                        <a class=" bold upper card-action aug_blue_btn text-right" href="http://www.petmemorial.com.br/" target="_blank">Clique Aqui</a>
                        </div>
                    </div>
                </div>
            </section>
        </div>
